"""預設資料：內建單字、每日一句／片語、每週計畫範本。"""

SEED_WORDS = [
    {"word": "accomplish", "meaning": "完成、達成", "example": "She accomplished her goal of reading 50 books this year."},
    {"word": "benefit", "meaning": "好處、益處", "example": "Regular exercise has many health benefits."},
    {"word": "consider", "meaning": "考慮、認為", "example": "Please consider my suggestion carefully."},
    {"word": "determine", "meaning": "決定、確定", "example": "The test will determine your English level."},
    {"word": "efficient", "meaning": "有效率的", "example": "This is a more efficient way to study vocabulary."},
    {"word": "fundamental", "meaning": "基本的、根本的", "example": "Grammar is fundamental to learning a language."},
    {"word": "generate", "meaning": "產生、生成", "example": "The app can generate a quiz from your word list."},
    {"word": "hesitate", "meaning": "猶豫", "example": "Don't hesitate to ask questions in class."},
    {"word": "improve", "meaning": "改善、進步", "example": "Reading every day will improve your English."},
    {"word": "justify", "meaning": "證明...正當、辯解", "example": "Can you justify your decision?"},
    {"word": "knowledge", "meaning": "知識", "example": "Knowledge of vocabulary helps with reading."},
    {"word": "luxury", "meaning": "奢侈、奢華", "example": "A daily walk is a small luxury for me."},
    {"word": "maintain", "meaning": "維持、保養", "example": "It's important to maintain a study routine."},
    {"word": "negotiate", "meaning": "談判、協商", "example": "They negotiated a better price."},
    {"word": "obstacle", "meaning": "障礙、阻礙", "example": "Fear of mistakes is a common obstacle for learners."},
    {"word": "participate", "meaning": "參與", "example": "Students should participate in class discussions."},
    {"word": "qualify", "meaning": "使合格、取得資格", "example": "She qualified for the advanced course."},
    {"word": "reliable", "meaning": "可靠的", "example": "He is a reliable study partner."},
    {"word": "significant", "meaning": "重要的、顯著的", "example": "You've made significant progress this month."},
    {"word": "transparent", "meaning": "透明的、清楚的", "example": "The teacher gave transparent feedback."},
    {"word": "analyze", "meaning": "分析", "example": "Let's analyze the data before deciding."},
    {"word": "approach", "meaning": "接近；方法", "example": "We need a new approach to this problem."},
    {"word": "assume", "meaning": "假定、認為", "example": "Don't assume he's wrong before you ask."},
    {"word": "available", "meaning": "可獲得的、有空的", "example": "Is this seat available?"},
    {"word": "brief", "meaning": "簡短的；摘要", "example": "Let me give you a brief summary."},
    {"word": "capable", "meaning": "有能力的", "example": "She is capable of handling the project alone."},
    {"word": "challenge", "meaning": "挑戰", "example": "Learning a language is a fun challenge."},
    {"word": "conclude", "meaning": "下結論、結束", "example": "We concluded the meeting at noon."},
    {"word": "contribute", "meaning": "貢獻、捐助", "example": "Everyone can contribute to the team."},
    {"word": "crucial", "meaning": "關鍵的、決定性的", "example": "This is a crucial moment for us."},
    {"word": "demonstrate", "meaning": "示範、證明", "example": "Let me demonstrate how it works."},
    {"word": "distribute", "meaning": "分配、分發", "example": "Please distribute these handouts."},
    {"word": "emphasize", "meaning": "強調", "example": "I want to emphasize this point."},
    {"word": "encounter", "meaning": "遭遇、偶遇", "example": "I encountered an old friend on the train."},
    {"word": "establish", "meaning": "建立、設立", "example": "They established the company in 1990."},
    {"word": "evaluate", "meaning": "評估、評價", "example": "We need to evaluate the results."},
    {"word": "evident", "meaning": "明顯的", "example": "His talent was evident from a young age."},
    {"word": "flexible", "meaning": "有彈性的、靈活的", "example": "My schedule is flexible this week."},
    {"word": "genuine", "meaning": "真正的、真誠的", "example": "She gave a genuine smile."},
    {"word": "gratitude", "meaning": "感激、感謝", "example": "I want to express my gratitude."},
    {"word": "immediate", "meaning": "立即的", "example": "We need an immediate response."},
    {"word": "inevitable", "meaning": "不可避免的", "example": "Change is inevitable."},
    {"word": "innovate", "meaning": "創新", "example": "Companies must innovate to survive."},
    {"word": "perceive", "meaning": "察覺、感知", "example": "How do you perceive this situation?"},
    {"word": "persuade", "meaning": "說服", "example": "I persuaded him to join us."},
    {"word": "precise", "meaning": "精確的", "example": "Please be precise about the time."},
    {"word": "priority", "meaning": "優先、優先事項", "example": "Safety is our top priority."},
    {"word": "reluctant", "meaning": "不情願的", "example": "He was reluctant to admit his mistake."},
    {"word": "resource", "meaning": "資源", "example": "Water is a precious resource."},
    {"word": "strategy", "meaning": "策略", "example": "We need a better marketing strategy."},
    {"word": "sufficient", "meaning": "足夠的", "example": "We have sufficient time to finish."},
]

DAILY_PHRASES = [
    {"en": "Practice makes perfect.", "zh": "熟能生巧。", "tag": "諺語"},
    {"en": "Rome wasn't built in a day.", "zh": "羅馬不是一天造成的。", "tag": "諺語"},
    {"en": "Better late than never.", "zh": "遲到總比不到好。", "tag": "諺語"},
    {"en": "Actions speak louder than words.", "zh": "行動勝於空談。", "tag": "諺語"},
    {"en": "The early bird catches the worm.", "zh": "早起的鳥兒有蟲吃。", "tag": "諺語"},
    {"en": "Don't put all your eggs in one basket.", "zh": "別把雞蛋放在同一個籃子裡。", "tag": "諺語"},
    {"en": "Every cloud has a silver lining.", "zh": "黑暗中總有一線光明。", "tag": "勵志"},
    {"en": "Where there's a will, there's a way.", "zh": "有志者事竟成。", "tag": "勵志"},
    {"en": "No pain, no gain.", "zh": "沒有付出就沒有收穫。", "tag": "勵志"},
    {"en": "Keep your chin up.", "zh": "別氣餒，振作起來。", "tag": "片語"},
    {"en": "Break a leg!", "zh": "祝你好運！(尤指演出前)", "tag": "片語"},
    {"en": "Hang in there.", "zh": "撐住、別放棄。", "tag": "片語"},
    {"en": "It's a piece of cake.", "zh": "這是小菜一碟。", "tag": "片語"},
    {"en": "Let's call it a day.", "zh": "今天就到此為止吧。", "tag": "片語"},
    {"en": "Slow and steady wins the race.", "zh": "穩紮穩打才能致勝。", "tag": "諺語"},
    {"en": "Knowledge is power.", "zh": "知識就是力量。", "tag": "勵志"},
    {"en": "A journey of a thousand miles begins with a single step.", "zh": "千里之行，始於足下。", "tag": "勵志"},
    {"en": "Look before you leap.", "zh": "三思而後行。", "tag": "諺語"},
    {"en": "Two heads are better than one.", "zh": "三個臭皮匠勝過一個諸葛亮。", "tag": "諺語"},
    {"en": "Make hay while the sun shines.", "zh": "把握時機。", "tag": "諺語"},
    {"en": "The grass is always greener on the other side.", "zh": "這山望著那山高。", "tag": "諺語"},
    {"en": "Don't count your chickens before they hatch.", "zh": "別打如意算盤。", "tag": "諺語"},
    {"en": "When in Rome, do as the Romans do.", "zh": "入境隨俗。", "tag": "諺語"},
    {"en": "Easy come, easy go.", "zh": "來得容易，去得快。", "tag": "諺語"},
    {"en": "You reap what you sow.", "zh": "種瓜得瓜，種豆得豆。", "tag": "諺語"},
    {"en": "Curiosity killed the cat.", "zh": "好奇心害死貓。", "tag": "諺語"},
    {"en": "Honesty is the best policy.", "zh": "誠實為上策。", "tag": "諺語"},
    {"en": "Time and tide wait for no man.", "zh": "歲月不饒人。", "tag": "諺語"},
    {"en": "A picture is worth a thousand words.", "zh": "一圖勝千言。", "tag": "諺語"},
    {"en": "Birds of a feather flock together.", "zh": "物以類聚。", "tag": "諺語"},
]

DEFAULT_WEEKLY_PLAN = [
    {"day": "週一", "task": "背 15 個新單字"},
    {"day": "週二", "task": "複習單字 + 做測驗"},
    {"day": "週三", "task": "閱讀一篇短文"},
    {"day": "週四", "task": "聽力練習 20 分鐘"},
    {"day": "週五", "task": "口說／跟讀練習"},
    {"day": "週六", "task": "看一集英文影集"},
    {"day": "週日", "task": "整週複習與整理"},
]
