"""情境對話 + 短篇故事範本(離線資料,不需 API)。

每筆 entry 含雙語對照 + 文法重點解說 + 例句。view_speak_story 渲染。
"""

CONVERSATIONS = [
    {
        "id": "cafe-order",
        "title": "在咖啡廳點餐",
        "level": "A2",
        "scene": "你走進星巴克想點一杯拿鐵跟一個瑪芬",
        "lines": [
            {"speaker": "你", "en": "Hi, can I get a tall latte, please?",
             "zh": "嗨，麻煩給我一杯中杯拿鐵。"},
            {"speaker": "店員", "en": "Sure! For here or to go?",
             "zh": "好的！內用還是外帶？"},
            {"speaker": "你", "en": "For here, thanks. Could I get oat milk instead?",
             "zh": "內用，謝謝。可以換成燕麥奶嗎？"},
            {"speaker": "店員", "en": "No problem. That'll be five dollars.",
             "zh": "沒問題，總共五美元。"},
            {"speaker": "你", "en": "Do you have any pastries today?",
             "zh": "今天有什麼麵包嗎？"},
            {"speaker": "店員", "en": "We've got blueberry muffins and croissants.",
             "zh": "我們有藍莓瑪芬跟可頌。"},
            {"speaker": "你", "en": "I'll take a muffin too, please.",
             "zh": "再給我一個瑪芬。"},
            {"speaker": "店員", "en": "Sounds good. What's your name?",
             "zh": "好的。請問貴姓？"},
            {"speaker": "你", "en": "It's Alex.",
             "zh": "我叫 Alex。"},
            {"speaker": "店員", "en": "Got it. We'll call you when it's ready.",
             "zh": "了解，好了會叫你。"},
        ],
        "grammar": [
            {"point": "Can I get / Could I get ...?",
             "explain": "點餐／請求最自然的禮貌說法。比 'I want...' 客氣 100 倍。"
                        "Could 比 Can 又更正式一點。",
             "examples": ["Can I get a coffee?", "Could I get the menu, please?",
                          "Can I get this in size 8?"]},
            {"point": "For here or to go?",
             "explain": "美式英語問內用／外帶的標準。英式講 eat in / take away。",
             "examples": ["For here, please.", "To go, thanks.",
                          "(British) Is that to eat in or take away?"]},
            {"point": "... instead",
             "explain": "「改成…」放句尾,替換掉預設選項。常用於點餐改成分／改方案。",
             "examples": ["Could I get soy milk instead?",
                          "I'll have tea instead of coffee.",
                          "Let's go on Sunday instead."]},
            {"point": "I'll take ...",
             "explain": "下訂時最自然的「我要這個」說法,比 I want 友善。",
             "examples": ["I'll take a muffin.", "I'll take two of those.",
                          "I'll take the red one."]},
        ],
    },
    {
        "id": "monday-chat",
        "title": "跟同事週一閒聊週末",
        "level": "A2-B1",
        "scene": "在茶水間遇到同事，閒聊兩分鐘",
        "lines": [
            {"speaker": "A", "en": "Morning! How was your weekend?",
             "zh": "早安！你週末過得怎樣？"},
            {"speaker": "B", "en": "Pretty chill, actually. I just stayed home and binged a show.",
             "zh": "其實蠻悠閒的，就待在家追劇。"},
            {"speaker": "A", "en": "Nice! What did you watch?",
             "zh": "不錯！你看了什麼？"},
            {"speaker": "B", "en": "This new K-drama everyone's talking about. It's addictive.",
             "zh": "大家在討論的那部新韓劇，超讓人上癮。"},
            {"speaker": "A", "en": "Oh, I've heard of that. Maybe I'll give it a try.",
             "zh": "喔我有聽過，那我也來看看好了。"},
            {"speaker": "B", "en": "You should! How about you? Did you do anything fun?",
             "zh": "你應該看！那你呢？做了什麼有趣的事嗎？"},
            {"speaker": "A", "en": "Not really. Just family stuff, you know.",
             "zh": "也沒什麼，就家庭事務，你懂的。"},
            {"speaker": "B", "en": "Yeah, I get that. Anyway, ready for the meeting at 10?",
             "zh": "嗯我懂。對了，10 點的會議準備好了沒？"},
            {"speaker": "A", "en": "Ugh, almost forgot. Better grab my notes.",
             "zh": "啊差點忘了，我去拿筆記。"},
        ],
        "grammar": [
            {"point": "How was your weekend?",
             "explain": "週一早上的萬用 small talk 開場。對方通常回 'Good, you?' 或具體事件。",
             "examples": ["How was your weekend?", "How was your trip?",
                          "How was the movie last night?"]},
            {"point": "Past Simple 過去簡單式",
             "explain": "問已發生的事都用 did + 原形。'Did you...?' 是 yes/no 問句最常見的開頭。",
             "examples": ["Did you watch the game?", "Did you do anything fun?",
                          "I stayed home / watched TV / binged a show."]},
            {"point": "Pretty + 形容詞",
             "explain": "口語表「蠻…的、相當…」,弱化或強化都行。比 very 更日常。",
             "examples": ["Pretty chill.", "Pretty tired today.", "Pretty good, thanks."]},
            {"point": "You know / I get that",
             "explain": "對話填充語(filler):'you know' 表「你懂的」、'I get that' 表「我懂」。"
                        "讓對話自然,母語人士每句都會塞。",
             "examples": ["Just family stuff, you know.",
                          "I get that. Same here.",
                          "It's been crazy, you know what I mean?"]},
        ],
    },
    {
        "id": "return-shoes",
        "title": "退換貨：鞋子尺寸不對",
        "level": "B1",
        "scene": "你在百貨公司買的鞋子大半號，回去換",
        "lines": [
            {"speaker": "你", "en": "Hi, I'd like to return these shoes.",
             "zh": "你好，我想退這雙鞋。"},
            {"speaker": "店員", "en": "Sure, do you have the receipt?",
             "zh": "好的，發票帶了嗎？"},
            {"speaker": "你", "en": "Yeah, here it is. They're the wrong size.",
             "zh": "有，在這裡。尺寸不對。"},
            {"speaker": "店員", "en": "No problem. Would you like a refund or an exchange?",
             "zh": "沒問題。您要退款還是換貨？"},
            {"speaker": "你", "en": "An exchange, if you have a size 8 in stock.",
             "zh": "如果有 8 號的話我想換貨。"},
            {"speaker": "店員", "en": "Let me check... Yes, we do. I'll bring them out.",
             "zh": "我查一下…有的，我去拿。"},
            {"speaker": "你", "en": "Great, thanks. How long does that usually take?",
             "zh": "謝謝，通常要等多久？"},
            {"speaker": "店員", "en": "Just a minute. The fitting room is right over there if you want to try them on.",
             "zh": "一下下而已。試衣間在那邊，您可以試穿。"},
            {"speaker": "你", "en": "Perfect.",
             "zh": "好的。"},
        ],
        "grammar": [
            {"point": "I'd like to ...",
             "explain": "I would like 的縮寫,比 I want 正式禮貌,適合店家／餐廳／客服等場景。",
             "examples": ["I'd like to return this.", "I'd like to make a reservation.",
                          "I'd like the steak, medium rare."]},
            {"point": "in stock / out of stock",
             "explain": "「有貨／沒貨」的標準說法。可問 'Do you have ... in stock?' ",
             "examples": ["Do you have this in stock?",
                          "Sorry, it's out of stock.",
                          "We have plenty in stock."]},
            {"point": "Let me check ...",
             "explain": "店員／客服爭取時間查資料的萬用句。後面常接 ... if we have it / your account。",
             "examples": ["Let me check the system.",
                          "Let me check if we have your size.",
                          "Let me check with my manager."]},
            {"point": "try ... on",
             "explain": "試穿衣服／鞋子,phrasal verb 順序:try + 名詞 + on，或 try them on。"
                        "代名詞必須插中間,不能說 try on them。",
             "examples": ["Can I try this on?", "Try them on first.",
                          "She tried it on but it didn't fit."]},
        ],
    },
    {
        "id": "work-stress",
        "title": "跟朋友抱怨工作壓力",
        "level": "B1",
        "scene": "下班後跟朋友訴苦",
        "lines": [
            {"speaker": "你", "en": "I'm so done with this week.",
             "zh": "我這週真的受夠了。"},
            {"speaker": "朋友", "en": "Tell me about it. What's going on?",
             "zh": "說來聽聽。怎麼了？"},
            {"speaker": "你", "en": "My boss keeps piling stuff on me. I had to stay late three nights in a row.",
             "zh": "老闆一直丟事情給我，連續三天加班。"},
            {"speaker": "朋友", "en": "That sucks. Did you talk to him?",
             "zh": "好慘。你有跟他說嗎？"},
            {"speaker": "你", "en": "I tried, but he just says everything is urgent.",
             "zh": "試過了，他只會說每件事都很急。"},
            {"speaker": "朋友", "en": "Yeah, that's frustrating. Have you thought about pushing back?",
             "zh": "對，這真的很煩。你有想過反推回去嗎？"},
            {"speaker": "你", "en": "I want to, but I'm worried about my year-end review.",
             "zh": "想啊，但我擔心年底考評。"},
            {"speaker": "朋友", "en": "Maybe just be honest about the workload. Most managers respect that.",
             "zh": "也許就誠實說工作量太大。大部分主管會尊重的。"},
            {"speaker": "你", "en": "You're right. I'll bring it up next week.",
             "zh": "你說的對，下週我會提出來。"},
        ],
        "grammar": [
            {"point": "I'm so done with ...",
             "explain": "口語「我受夠…了」,語氣強烈,用在抱怨；done with 後接事物。",
             "examples": ["I'm so done with this job.",
                          "I'm done with his excuses.",
                          "I'm done with dating apps."]},
            {"point": "keep + Ving",
             "explain": "「一直在做…」,表持續或重複的動作,常用在抱怨。",
             "examples": ["He keeps piling stuff on me.",
                          "She keeps calling me late at night.",
                          "It keeps raining."]},
            {"point": "... in a row",
             "explain": "「連續…次／天」,放在數字後。常搭 days / weeks / times。",
             "examples": ["three nights in a row",
                          "won five games in a row",
                          "the third time in a row I've missed the bus"]},
            {"point": "Have you thought about + Ving?",
             "explain": "委婉提建議:「你有想過…嗎？」比 'You should...' 不像命令。",
             "examples": ["Have you thought about taking a break?",
                          "Have you thought about asking for help?",
                          "Have you thought about switching jobs?"]},
            {"point": "bring it up",
             "explain": "phrasal verb,「提出來、提及」(議題、問題);常用於工作會議或對話。",
             "examples": ["I'll bring it up next week.",
                          "She brought up the budget issue.",
                          "Don't bring that up at dinner."]},
        ],
    },
    {
        "id": "rent-apartment",
        "title": "看房子跟房東談條件",
        "level": "B1-B2",
        "scene": "你看到網路廣告約看一間兩房公寓，現場跟房東談價格與設施",
        "lines": [
            {"speaker": "你", "en": "Hi, I saw the listing online. Is the apartment still available?",
             "zh": "你好，我看到網路上的廣告，這間還有沒有人租？"},
            {"speaker": "房東", "en": "Yes, it's available from next month. Want to take a look?",
             "zh": "有，下個月可以入住。要進來看看嗎？"},
            {"speaker": "你", "en": "Sure. Could you tell me what's included in the rent?",
             "zh": "好，請問月租包含什麼？"},
            {"speaker": "房東", "en": "Water and Wi-Fi are covered, but electricity is on you.",
             "zh": "水費和網路都含，但電費自付。"},
            {"speaker": "你", "en": "Got it. Is the furniture included?",
             "zh": "了解。家具有附嗎？"},
            {"speaker": "房東", "en": "Most of it — bed, sofa, kitchen appliances. Just bring your clothes.",
             "zh": "幾乎都有：床、沙發、廚房家電。你只要帶衣服進來。"},
            {"speaker": "你", "en": "What about the deposit?",
             "zh": "押金多少？"},
            {"speaker": "房東", "en": "Two months' rent, refundable when you move out, assuming no damage.",
             "zh": "兩個月房租，退租時退還，前提是沒有損壞。"},
            {"speaker": "你", "en": "Sounds reasonable. Would you be open to a one-year lease?",
             "zh": "聽起來合理。可以考慮簽一年約嗎？"},
            {"speaker": "房東", "en": "Yes, and if you sign for two years, I can knock $50 off the monthly rent.",
             "zh": "可以，如果你簽兩年，我可以每月少收 50 美元。"},
            {"speaker": "你", "en": "Tempting. Let me think it over and get back to you tomorrow.",
             "zh": "蠻吸引人的。我考慮一下，明天回覆你。"},
            {"speaker": "房東", "en": "No rush. Just let me know by Friday.",
             "zh": "不急，星期五前告訴我就好。"},
        ],
        "grammar": [
            {"point": "Is X available? / available from + 時間",
             "explain": "「還有沒有」「從何時開始可以」的標準說法。租房、餐廳訂位、課程詢問都用。",
             "examples": ["Is the apartment still available?",
                          "We're available from Monday.",
                          "The room is available from June 1st."]},
            {"point": "What's included in ...?",
             "explain": "詢問「包含什麼」。租金、套餐、保險、會員都常見。",
             "examples": ["What's included in the rent?",
                          "What's included in the package?",
                          "Is breakfast included?"]},
            {"point": "be on you / on me — 慣用語「由 X 負責付」",
             "explain": "電費／午餐／這頓你出我出。on me 也用於「我請客」。",
             "examples": ["Electricity is on you.",
                          "Lunch is on me today.",
                          "The drinks are on the house. (店家請客)"]},
            {"point": "Would you be open to ...?",
             "explain": "委婉提協商方案。比 'Can we...?' 更尊重對方,商業情境很實用。",
             "examples": ["Would you be open to a one-year lease?",
                          "Would you be open to remote work?",
                          "Would you be open to a discount?"]},
            {"point": "let me think it over / get back to you",
             "explain": "商業／租房／買東西的「延後決定」禮儀組合。",
             "examples": ["Let me think it over.",
                          "I'll get back to you tomorrow.",
                          "Can I sleep on it? (讓我想一晚)"]},
        ],
    },
    {
        "id": "job-interview",
        "title": "工程師面試自介 + 弱點 + Q&A",
        "level": "B1-B2",
        "scene": "面試前 5–10 分鐘的標準開場",
        "lines": [
            {"speaker": "面試官", "en": "Thanks for coming in. Tell me a bit about yourself.",
             "zh": "謝謝你來。請你簡單自我介紹。"},
            {"speaker": "你", "en": "Sure. I'm a backend engineer with five years of experience, mostly with Python and AWS.",
             "zh": "好的。我是後端工程師，五年經驗，主要用 Python 與 AWS。"},
            {"speaker": "面試官", "en": "Nice. What made you apply to our company?",
             "zh": "不錯。你為什麼想加入我們公司？"},
            {"speaker": "你", "en": "Honestly, I've been following your AI team's work for a while, and I'd love to contribute.",
             "zh": "老實說，我關注你們 AI 團隊的成果一段時間了，很想加入貢獻。"},
            {"speaker": "面試官", "en": "That's great to hear. What would you say is your biggest weakness?",
             "zh": "很高興聽到。那你覺得自己最大的弱點是什麼？"},
            {"speaker": "你", "en": "I tend to over-prepare before meetings. It sometimes slows me down. I'm working on trusting my instincts more.",
             "zh": "我會傾向會議前過度準備，有時反而拖慢進度。我正努力學會更相信直覺。"},
            {"speaker": "面試官", "en": "Fair enough. Can you walk me through a project you're proud of?",
             "zh": "可以理解。可以跟我聊聊你最自豪的專案嗎？"},
            {"speaker": "你", "en": "Sure. Last year I led a team to migrate a legacy system to microservices. We cut latency by 40%.",
             "zh": "好。去年我帶團隊把舊系統遷移到微服務，把延遲降低了 40%。"},
            {"speaker": "面試官", "en": "Impressive. Any questions for us?",
             "zh": "很厲害。你有什麼問題想問我們的嗎？"},
            {"speaker": "你", "en": "Yes — how does your team usually handle code reviews?",
             "zh": "有的，你們團隊通常怎麼做 code review？"},
            {"speaker": "面試官", "en": "We do them in pairs. Most reviews are turned around within a day.",
             "zh": "我們兩人一組做。大部分 review 一天內會完成。"},
        ],
        "grammar": [
            {"point": "I'm a [職位] with [N years] of experience",
             "explain": "面試自介公式,簡潔有力。後面加 mostly with / specialized in [技能]。",
             "examples": ["I'm a backend engineer with 5 years of experience.",
                          "I'm a designer with 3 years of experience in UX.",
                          "I'm a PM with 7 years of experience leading global teams."]},
            {"point": "What made you ...?",
             "explain": "問動機比 'Why did you...?' 自然、不帶質問感。",
             "examples": ["What made you apply to our company?",
                          "What made you switch careers?",
                          "What made you choose this product?"]},
            {"point": "I'd love to + V",
             "explain": "委婉強烈意願,比 'I want to' 客氣得多。面試、社交都好用。",
             "examples": ["I'd love to contribute to your team.",
                          "I'd love to learn more about that.",
                          "I'd love to grab coffee sometime."]},
            {"point": "I tend to + V / I'm working on + Ving",
             "explain": "回答「弱點」黃金組合:承認傾向 + 主動改善。比 'My weakness is...' 高級。",
             "examples": ["I tend to over-prepare.",
                          "I tend to overthink decisions.",
                          "I'm working on delegating more."]},
            {"point": "walk me through ... / led a team to ... / cut X by N%",
             "explain": "面試「描述成就」三件套:導覽動作 + 領導動詞 + 量化成果（數字 + by）。",
             "examples": ["Can you walk me through your decision?",
                          "I led a team of 8 engineers.",
                          "We cut costs by 30% / improved efficiency by 50%."]},
        ],
    },
    {
        "id": "see-doctor",
        "title": "看醫生：喉嚨痛兩天",
        "level": "B1",
        "scene": "你喉嚨痛兩天，掛了診所的號",
        "lines": [
            {"speaker": "醫生", "en": "Hi, what brings you in today?",
             "zh": "你好，今天怎麼不舒服？"},
            {"speaker": "你", "en": "I've had a sore throat for two days, and it's getting worse.",
             "zh": "我喉嚨痛兩天了，而且越來越嚴重。"},
            {"speaker": "醫生", "en": "Any fever or cough?",
             "zh": "有發燒或咳嗽嗎？"},
            {"speaker": "你", "en": "A mild fever last night, around 38. I'm coughing a bit too.",
             "zh": "昨晚有點微燒大概 38 度，也有一點咳。"},
            {"speaker": "醫生", "en": "Let me take a look. Open wide and say 'ah.'",
             "zh": "我看一下。張大嘴說「啊」。"},
            {"speaker": "你", "en": "Ahhh.",
             "zh": "啊──"},
            {"speaker": "醫生", "en": "Your throat is pretty red. Have you been around anyone sick lately?",
             "zh": "你喉嚨蠻紅的。最近有接觸過生病的人嗎？"},
            {"speaker": "你", "en": "My coworker had the flu last week.",
             "zh": "我同事上週感冒。"},
            {"speaker": "醫生", "en": "That'd explain it. I'll prescribe some throat lozenges and an anti-inflammatory.",
             "zh": "那就解釋得通了。我開喉糖跟消炎藥給你。"},
            {"speaker": "你", "en": "Do I need antibiotics?",
             "zh": "需要吃抗生素嗎？"},
            {"speaker": "醫生", "en": "Not yet. Let's see how you feel in three days. Plenty of fluids and rest.",
             "zh": "先不用，三天後看狀況。多喝水多休息。"},
            {"speaker": "你", "en": "Got it. Thank you, doctor.",
             "zh": "好的，謝謝醫生。"},
        ],
        "grammar": [
            {"point": "What brings you in (today)?",
             "explain": "醫師看診標準開場,比 'Why are you here?' 友善。也用於律師、客服。",
             "examples": ["What brings you in today?",
                          "What brings you to our clinic?",
                          "What brings you in this fine morning?"]},
            {"point": "I've had X for Y days — 現在完成式 + 持續時間",
             "explain": "症狀持續多久必用現在完成式 (have/has + 過去分詞 + for / since)。",
             "examples": ["I've had a sore throat for two days.",
                          "I've had headaches since Monday.",
                          "She's had a fever for 24 hours."]},
            {"point": "it's getting + 比較級",
             "explain": "現在進行式 + 比較級表「越來越…」的趨勢。症狀、天氣、學習進度都常用。",
             "examples": ["It's getting worse.",
                          "It's getting cold.",
                          "My English is getting better."]},
            {"point": "Have you been around / Have you been + Ving?",
             "explain": "現在完成式問「最近做了/接觸過什麼」,常用於醫療問診、追溯接觸史。",
             "examples": ["Have you been around anyone sick?",
                          "Have you been traveling recently?",
                          "Have you been taking your medication?"]},
            {"point": "I'll prescribe ... / antibiotics / fluids and rest",
             "explain": "看醫生標準收尾組合:開藥 + 醫囑。fluids = 多喝水的口語講法。",
             "examples": ["I'll prescribe an antibiotic.",
                          "Drink plenty of fluids.",
                          "Get plenty of rest and take it easy."]},
        ],
    },
    {
        "id": "weekend-plan",
        "title": "跟朋友約週末爬山",
        "level": "A2-B1",
        "scene": "禮拜三在 LINE 上敲朋友週末有沒有空",
        "lines": [
            {"speaker": "你", "en": "Hey, are you free this Saturday?",
             "zh": "嘿，這週六有空嗎？"},
            {"speaker": "朋友", "en": "I think so. What's up?",
             "zh": "應該有，怎麼了？"},
            {"speaker": "你", "en": "A few of us are going hiking. Want to come?",
             "zh": "我們幾個要去爬山，你要一起嗎？"},
            {"speaker": "朋友", "en": "That sounds fun! Where are you going?",
             "zh": "聽起來不錯！要去哪？"},
            {"speaker": "你", "en": "Yangmingshan, the easy trail. We'll start around 9.",
             "zh": "陽明山，走簡單的路線。九點左右出發。"},
            {"speaker": "朋友", "en": "Cool. Should I bring anything?",
             "zh": "好。要帶什麼嗎？"},
            {"speaker": "你", "en": "Maybe water and a snack. We're getting lunch after.",
             "zh": "水跟點心吧，午餐回來再吃。"},
            {"speaker": "朋友", "en": "Got it. Let's meet at the MRT station?",
             "zh": "了解。我們在捷運站碰面？"},
            {"speaker": "你", "en": "Sure, see you at 8:45 then.",
             "zh": "好，那 8:45 見。"},
        ],
        "grammar": [
            {"point": "Are you free + 時間?",
             "explain": "問對方有無空檔的標準說法。比 'Do you have time?' 自然。",
             "examples": ["Are you free this Saturday?",
                          "Are you free tonight?",
                          "Are you free for lunch tomorrow?"]},
            {"point": "Want to + V? / Wanna ...?",
             "explain": "非正式邀請,省略 Do you。Want to 在口語常縮成 wanna。",
             "examples": ["Want to come?", "Wanna grab dinner?",
                          "Wanna come over for a movie?"]},
            {"point": "Should I bring anything?",
             "explain": "去別人家／聚會時的禮貌問句。回答常是 'Just yourself' 或具體物品。",
             "examples": ["Should I bring anything?",
                          "What should I wear?",
                          "Should I bring my laptop?"]},
            {"point": "現在進行式表未來",
             "explain": "be + Ving 也能表「已定好的未來計畫」,語感比 will 更確定。",
             "examples": ["A few of us are going hiking.",
                          "I'm meeting Sara at 7.",
                          "We're flying to Japan next month."]},
        ],
    },
]


STORIES = [
    {
        "id": "morning-routine",
        "title": "My Morning Routine",
        "level": "A2",
        "scene": "用現在式練習描述每天的習慣",
        "paragraphs": [
            {"en": "I usually wake up at 7 AM. As soon as my alarm rings, I drink a big glass of water. Then I go to the bathroom and brush my teeth.",
             "zh": "我通常早上 7 點起床。鬧鐘一響我就喝一大杯水，然後去浴室刷牙。"},
            {"en": "I prefer cold showers because they wake me up fast. Around 7:30, I make a quick breakfast — usually toast and eggs.",
             "zh": "我喜歡洗冷水澡，因為能很快醒過來。7:30 左右我做個簡單的早餐，通常是吐司加蛋。"},
            {"en": "While I eat, I check my phone for messages. After breakfast, I get dressed and pack my bag for work.",
             "zh": "邊吃邊看手機訊息。吃完早餐後，我換衣服、準備上班用的包包。"},
            {"en": "I leave the house at 8:15 to catch the bus. The ride takes about 30 minutes, so I usually listen to a podcast or read a book.",
             "zh": "8:15 出門去搭公車。車程大約 30 分鐘，我通常聽 podcast 或看書。"},
            {"en": "By 9 AM, I'm at my desk and ready to start the day. It's a simple routine, but it keeps me organized.",
             "zh": "九點前我就坐到位子上，準備好開始工作。這個習慣很簡單，但讓我生活很有條理。"},
        ],
        "grammar": [
            {"point": "Simple Present 現在式 — 描述習慣／日常",
             "explain": "重複發生的事用現在式,動詞用原形（第三人稱單數加 s/es）。"
                        "搭配 usually / always / often / every day。",
             "examples": ["I usually wake up at 7 AM.",
                          "She drinks coffee every morning.",
                          "We go to the gym on weekends."]},
            {"point": "as soon as ... — 「一…就…」",
             "explain": "時間連接詞,兩個動作緊接著發生。子句用現在式（即使指未來）。",
             "examples": ["As soon as my alarm rings, I drink water.",
                          "Call me as soon as you arrive.",
                          "She left as soon as it started raining."]},
            {"point": "時間介系詞 at / around / by",
             "explain": "at 用於精確時間（at 7 AM）；around 用於大約（around 7:30）；"
                        "by 用於「在…之前／到…為止」(by 9 AM = 不晚於 9 點)。",
             "examples": ["I wake up at 7 AM.",
                          "Around 7:30, I make breakfast.",
                          "By 9 AM, I'm at my desk."]},
            {"point": "While + 子句 / After + 名詞",
             "explain": "while 表「在…同時」(後接子句);after 後可接名詞或子句。",
             "examples": ["While I eat, I check my phone.",
                          "After breakfast, I get dressed.",
                          "After I finished work, I went home."]},
        ],
    },
    {
        "id": "best-trip",
        "title": "The Best Trip I Ever Took",
        "level": "B1",
        "scene": "用過去式與完成式講一段回憶",
        "paragraphs": [
            {"en": "Two summers ago, I went to Kyoto with my best friend. It was my first time visiting Japan, and I had been dreaming about it for years.",
             "zh": "兩年前的夏天，我跟最好的朋友去京都。那是我第一次去日本，我已經夢想了好多年。"},
            {"en": "We stayed in a small ryokan in Gion. The host welcomed us with green tea and rice crackers. That evening, we walked through the old streets, and I felt like I had stepped into a movie.",
             "zh": "我們住在祇園的一家小旅館。老闆娘用抹茶跟米菓招待我們。那天傍晚我們走過古老的街道，我覺得自己彷彿走進了一部電影。"},
            {"en": "The next day, we visited Fushimi Inari Shrine. Climbing all those red gates took almost three hours, but the view from the top was worth every step. I had never seen anything so beautiful.",
             "zh": "隔天我們去了伏見稻荷大社。爬完那些紅色鳥居花了快三小時，但山頂的景色每一步都值得。我從沒見過這麼美的景色。"},
            {"en": "By the end of the trip, I'd taken over 500 photos. We promised each other we'd go back someday. I haven't made it yet, but I will.",
             "zh": "旅程結束時，我已經拍了 500 多張照片。我們約定有一天要再回去。雖然到現在還沒實現，但我一定會的。"},
        ],
        "grammar": [
            {"point": "Past Simple 過去簡單式 — 已完成的單一事件",
             "explain": "動詞變過去式 (went / stayed / visited / took)。"
                        "敘述故事的主幹時態,通常搭配明確時間（two summers ago, that evening）。",
             "examples": ["I went to Kyoto.",
                          "We stayed in a ryokan.",
                          "We visited the shrine."]},
            {"point": "Past Perfect 過去完成式 — 「過去的過去」",
             "explain": "had + 過去分詞。表示某動作在「另一個過去事件」之前就完成了。"
                        "常與 had been ... for years（已經…好幾年了）一起用。",
             "examples": ["I had been dreaming about it for years.",
                          "I felt like I had stepped into a movie.",
                          "I had never seen anything so beautiful."]},
            {"point": "Present Perfect 現在完成式 — 從過去持續到現在",
             "explain": "have/has + 過去分詞。表示「到現在為止」的狀態或未完成的事。"
                        "haven't ... yet 是「還沒…」的固定組合。",
             "examples": ["I haven't made it back yet.",
                          "I've been to Japan twice.",
                          "She has never tried sushi."]},
            {"point": "would 表「過去的未來」",
             "explain": "在過去視角下講「會做的事」,常用於間接引述。"
                        "We promised we'd go back = We promised we would go back。",
             "examples": ["We promised we'd go back.",
                          "He said he would call.",
                          "I knew it would be hard."]},
        ],
    },
    {
        "id": "why-english",
        "title": "Why I Started Learning English",
        "level": "B2",
        "scene": "個人成長敘事，用分詞構句、第三條件式、現在完成進行式等進階句型",
        "paragraphs": [
            {"en": "Looking back, I didn't always love English. In high school, it was just another subject I had to pass — full of grammar rules I didn't understand and vocabulary I couldn't remember.",
             "zh": "回想起來，我並不是一直都熱愛英文。高中時，它只是另一個必須通過的科目──滿是看不懂的文法規則和記不起來的單字。"},
            {"en": "Everything changed when I was 22. I had just graduated and was working part-time at a small startup. My boss handed me an email from a Singaporean client and asked me to draft a reply. I froze.",
             "zh": "一切在我 22 歲時改變了。我剛畢業，正在一家小型新創公司打工。老闆遞給我一封新加坡客戶的信，要我擬一份回覆。我整個僵住。"},
            {"en": "Despite six years of formal English classes, I couldn't write more than two sentences without checking a dictionary. That night, I felt ashamed — not because I lacked vocabulary, but because I had wasted years memorizing words I never used.",
             "zh": "儘管學了六年正規英文，我連兩句話都寫不出來，不查字典就停不下來。那天晚上我感到羞愧──不是因為單字不夠，而是因為我浪費了好幾年背一堆從不使用的字。"},
            {"en": "If I hadn't been forced to write that email, I might still be stuck in the same place. The next morning, I changed my approach. Instead of studying grammar tables, I started watching podcasts during my commute and focusing on phrases real people actually use.",
             "zh": "如果不是被迫寫那封信，我可能還困在原地。隔天我改變了方法──不再死啃文法表，而是通勤時開始看 podcast，專注在母語人士真正會用的詞句。"},
            {"en": "Three years later, I can hold real conversations, write emails confidently, and even crack jokes in English. I'm not fluent yet — fluency is a moving target — but I'm no longer afraid.",
             "zh": "三年後的今天，我能進行真正的對話、自信地寫信、甚至能用英文開玩笑。我還沒到流利的程度──流利是個會移動的目標──但我不再害怕了。"},
            {"en": "Looking back, my biggest regret is not starting sooner. If you're reading this and feeling stuck, just start. The hardest part isn't grammar; it's the courage to begin.",
             "zh": "回頭看，我最大的遺憾是沒有早點開始。如果你正在讀這段文字、感覺卡住了，那就開始吧。最難的不是文法，而是踏出第一步的勇氣。"},
        ],
        "grammar": [
            {"point": "Looking back, ... — 分詞構句 (Participial Phrase) 開頭",
             "explain": "用 V-ing 取代「When I look back, ...」這類副詞子句,文學感強,B2 必備。"
                        "句首的分詞構句主詞必須與主句一致。",
             "examples": ["Looking back, I didn't always love English.",
                          "Walking down the street, I bumped into an old friend.",
                          "Having finished the report, she went home."]},
            {"point": "Past Perfect 過去完成式串接時序",
             "explain": "敘事時若要回到「更早的過去」,用 had + p.p.。"
                        "「我剛畢業」(had just graduated)、「我浪費了幾年」(had wasted) 都在故事主時間軸更之前。",
             "examples": ["I had just graduated when this happened.",
                          "She had wasted years memorizing useless words.",
                          "By the time I arrived, they had already left."]},
            {"point": "第三條件式 (Third Conditional) — 「過去如果…就…」",
             "explain": "If + had + p.p., S + would/might + have + p.p. (純假設過去未發生的事)。"
                        "本文用變形:If I hadn't been forced..., I might still be stuck — 結果延續至今用 might still be。",
             "examples": ["If I hadn't been forced to write that email, I might still be stuck.",
                          "If she had studied harder, she would have passed.",
                          "If you'd told me earlier, I could have helped."]},
            {"point": "Instead of + Ving — 「不再做 X,改做 Y」",
             "explain": "instead of 後一定接「名詞或 Ving」,不是 to V。常用於對比兩種做法。",
             "examples": ["Instead of studying grammar tables, I started watching podcasts.",
                          "Instead of complaining, try to find a solution.",
                          "She walked instead of taking the bus."]},
            {"point": "no longer + V/Adj. — 「不再…」",
             "explain": "比 'not anymore' 正式,常用於書面或情緒高潮處。位置在 be 動詞後、助動詞後、實義動詞前。",
             "examples": ["I'm no longer afraid.",
                          "She no longer works here.",
                          "He could no longer pretend."]},
            {"point": "強調對比:The hardest part isn't X; it's Y",
             "explain": "用「不是 X，是 Y」的對比結構作收尾金句,文章與演講都很有力。",
             "examples": ["The hardest part isn't grammar; it's the courage to begin.",
                          "It's not about money; it's about respect.",
                          "What matters isn't speed; it's consistency."]},
        ],
    },
]
