"""情境對話 + 短篇故事範本(離線資料,不需 API)。

每筆 entry 含雙語對照 + 文法重點解說 + 例句。view_speak_story 渲染。
"""

CONVERSATIONS = [
    {
        "id": "cafe-order",
        "title": "在咖啡廳點餐",
        "level": "A2",
        "scene": "你走進星巴克想點一杯拿鐵跟一個瑪芬",
        "lines": [
            {"speaker": "你", "en": "Hi, can I get a tall latte, please?",
             "zh": "嗨，麻煩給我一杯中杯拿鐵。"},
            {"speaker": "店員", "en": "Sure! For here or to go?",
             "zh": "好的！內用還是外帶？"},
            {"speaker": "你", "en": "For here, thanks. Could I get oat milk instead?",
             "zh": "內用，謝謝。可以換成燕麥奶嗎？"},
            {"speaker": "店員", "en": "No problem. That'll be five dollars.",
             "zh": "沒問題，總共五美元。"},
            {"speaker": "你", "en": "Do you have any pastries today?",
             "zh": "今天有什麼麵包嗎？"},
            {"speaker": "店員", "en": "We've got blueberry muffins and croissants.",
             "zh": "我們有藍莓瑪芬跟可頌。"},
            {"speaker": "你", "en": "I'll take a muffin too, please.",
             "zh": "再給我一個瑪芬。"},
            {"speaker": "店員", "en": "Sounds good. What's your name?",
             "zh": "好的。請問貴姓？"},
            {"speaker": "你", "en": "It's Alex.",
             "zh": "我叫 Alex。"},
            {"speaker": "店員", "en": "Got it. We'll call you when it's ready.",
             "zh": "了解，好了會叫你。"},
        ],
        "grammar": [
            {"point": "Can I get / Could I get ...?",
             "explain": "點餐／請求最自然的禮貌說法。比 'I want...' 客氣 100 倍。"
                        "Could 比 Can 又更正式一點。",
             "examples": ["Can I get a coffee?", "Could I get the menu, please?",
                          "Can I get this in size 8?"]},
            {"point": "For here or to go?",
             "explain": "美式英語問內用／外帶的標準。英式講 eat in / take away。",
             "examples": ["For here, please.", "To go, thanks.",
                          "(British) Is that to eat in or take away?"]},
            {"point": "... instead",
             "explain": "「改成…」放句尾,替換掉預設選項。常用於點餐改成分／改方案。",
             "examples": ["Could I get soy milk instead?",
                          "I'll have tea instead of coffee.",
                          "Let's go on Sunday instead."]},
            {"point": "I'll take ...",
             "explain": "下訂時最自然的「我要這個」說法,比 I want 友善。",
             "examples": ["I'll take a muffin.", "I'll take two of those.",
                          "I'll take the red one."]},
        ],
    },
    {
        "id": "monday-chat",
        "title": "跟同事週一閒聊週末",
        "level": "A2-B1",
        "scene": "在茶水間遇到同事，閒聊兩分鐘",
        "lines": [
            {"speaker": "A", "en": "Morning! How was your weekend?",
             "zh": "早安！你週末過得怎樣？"},
            {"speaker": "B", "en": "Pretty chill, actually. I just stayed home and binged a show.",
             "zh": "其實蠻悠閒的，就待在家追劇。"},
            {"speaker": "A", "en": "Nice! What did you watch?",
             "zh": "不錯！你看了什麼？"},
            {"speaker": "B", "en": "This new K-drama everyone's talking about. It's addictive.",
             "zh": "大家在討論的那部新韓劇，超讓人上癮。"},
            {"speaker": "A", "en": "Oh, I've heard of that. Maybe I'll give it a try.",
             "zh": "喔我有聽過，那我也來看看好了。"},
            {"speaker": "B", "en": "You should! How about you? Did you do anything fun?",
             "zh": "你應該看！那你呢？做了什麼有趣的事嗎？"},
            {"speaker": "A", "en": "Not really. Just family stuff, you know.",
             "zh": "也沒什麼，就家庭事務，你懂的。"},
            {"speaker": "B", "en": "Yeah, I get that. Anyway, ready for the meeting at 10?",
             "zh": "嗯我懂。對了，10 點的會議準備好了沒？"},
            {"speaker": "A", "en": "Ugh, almost forgot. Better grab my notes.",
             "zh": "啊差點忘了，我去拿筆記。"},
        ],
        "grammar": [
            {"point": "How was your weekend?",
             "explain": "週一早上的萬用 small talk 開場。對方通常回 'Good, you?' 或具體事件。",
             "examples": ["How was your weekend?", "How was your trip?",
                          "How was the movie last night?"]},
            {"point": "Past Simple 過去簡單式",
             "explain": "問已發生的事都用 did + 原形。'Did you...?' 是 yes/no 問句最常見的開頭。",
             "examples": ["Did you watch the game?", "Did you do anything fun?",
                          "I stayed home / watched TV / binged a show."]},
            {"point": "Pretty + 形容詞",
             "explain": "口語表「蠻…的、相當…」,弱化或強化都行。比 very 更日常。",
             "examples": ["Pretty chill.", "Pretty tired today.", "Pretty good, thanks."]},
            {"point": "You know / I get that",
             "explain": "對話填充語(filler):'you know' 表「你懂的」、'I get that' 表「我懂」。"
                        "讓對話自然,母語人士每句都會塞。",
             "examples": ["Just family stuff, you know.",
                          "I get that. Same here.",
                          "It's been crazy, you know what I mean?"]},
        ],
    },
    {
        "id": "return-shoes",
        "title": "退換貨：鞋子尺寸不對",
        "level": "B1",
        "scene": "你在百貨公司買的鞋子大半號，回去換",
        "lines": [
            {"speaker": "你", "en": "Hi, I'd like to return these shoes.",
             "zh": "你好，我想退這雙鞋。"},
            {"speaker": "店員", "en": "Sure, do you have the receipt?",
             "zh": "好的，發票帶了嗎？"},
            {"speaker": "你", "en": "Yeah, here it is. They're the wrong size.",
             "zh": "有，在這裡。尺寸不對。"},
            {"speaker": "店員", "en": "No problem. Would you like a refund or an exchange?",
             "zh": "沒問題。您要退款還是換貨？"},
            {"speaker": "你", "en": "An exchange, if you have a size 8 in stock.",
             "zh": "如果有 8 號的話我想換貨。"},
            {"speaker": "店員", "en": "Let me check... Yes, we do. I'll bring them out.",
             "zh": "我查一下…有的，我去拿。"},
            {"speaker": "你", "en": "Great, thanks. How long does that usually take?",
             "zh": "謝謝，通常要等多久？"},
            {"speaker": "店員", "en": "Just a minute. The fitting room is right over there if you want to try them on.",
             "zh": "一下下而已。試衣間在那邊，您可以試穿。"},
            {"speaker": "你", "en": "Perfect.",
             "zh": "好的。"},
        ],
        "grammar": [
            {"point": "I'd like to ...",
             "explain": "I would like 的縮寫,比 I want 正式禮貌,適合店家／餐廳／客服等場景。",
             "examples": ["I'd like to return this.", "I'd like to make a reservation.",
                          "I'd like the steak, medium rare."]},
            {"point": "in stock / out of stock",
             "explain": "「有貨／沒貨」的標準說法。可問 'Do you have ... in stock?' ",
             "examples": ["Do you have this in stock?",
                          "Sorry, it's out of stock.",
                          "We have plenty in stock."]},
            {"point": "Let me check ...",
             "explain": "店員／客服爭取時間查資料的萬用句。後面常接 ... if we have it / your account。",
             "examples": ["Let me check the system.",
                          "Let me check if we have your size.",
                          "Let me check with my manager."]},
            {"point": "try ... on",
             "explain": "試穿衣服／鞋子,phrasal verb 順序:try + 名詞 + on，或 try them on。"
                        "代名詞必須插中間,不能說 try on them。",
             "examples": ["Can I try this on?", "Try them on first.",
                          "She tried it on but it didn't fit."]},
        ],
    },
    {
        "id": "work-stress",
        "title": "跟朋友抱怨工作壓力",
        "level": "B1",
        "scene": "下班後跟朋友訴苦",
        "lines": [
            {"speaker": "你", "en": "I'm so done with this week.",
             "zh": "我這週真的受夠了。"},
            {"speaker": "朋友", "en": "Tell me about it. What's going on?",
             "zh": "說來聽聽。怎麼了？"},
            {"speaker": "你", "en": "My boss keeps piling stuff on me. I had to stay late three nights in a row.",
             "zh": "老闆一直丟事情給我，連續三天加班。"},
            {"speaker": "朋友", "en": "That sucks. Did you talk to him?",
             "zh": "好慘。你有跟他說嗎？"},
            {"speaker": "你", "en": "I tried, but he just says everything is urgent.",
             "zh": "試過了，他只會說每件事都很急。"},
            {"speaker": "朋友", "en": "Yeah, that's frustrating. Have you thought about pushing back?",
             "zh": "對，這真的很煩。你有想過反推回去嗎？"},
            {"speaker": "你", "en": "I want to, but I'm worried about my year-end review.",
             "zh": "想啊，但我擔心年底考評。"},
            {"speaker": "朋友", "en": "Maybe just be honest about the workload. Most managers respect that.",
             "zh": "也許就誠實說工作量太大。大部分主管會尊重的。"},
            {"speaker": "你", "en": "You're right. I'll bring it up next week.",
             "zh": "你說的對，下週我會提出來。"},
        ],
        "grammar": [
            {"point": "I'm so done with ...",
             "explain": "口語「我受夠…了」,語氣強烈,用在抱怨；done with 後接事物。",
             "examples": ["I'm so done with this job.",
                          "I'm done with his excuses.",
                          "I'm done with dating apps."]},
            {"point": "keep + Ving",
             "explain": "「一直在做…」,表持續或重複的動作,常用在抱怨。",
             "examples": ["He keeps piling stuff on me.",
                          "She keeps calling me late at night.",
                          "It keeps raining."]},
            {"point": "... in a row",
             "explain": "「連續…次／天」,放在數字後。常搭 days / weeks / times。",
             "examples": ["three nights in a row",
                          "won five games in a row",
                          "the third time in a row I've missed the bus"]},
            {"point": "Have you thought about + Ving?",
             "explain": "委婉提建議:「你有想過…嗎？」比 'You should...' 不像命令。",
             "examples": ["Have you thought about taking a break?",
                          "Have you thought about asking for help?",
                          "Have you thought about switching jobs?"]},
            {"point": "bring it up",
             "explain": "phrasal verb,「提出來、提及」(議題、問題);常用於工作會議或對話。",
             "examples": ["I'll bring it up next week.",
                          "She brought up the budget issue.",
                          "Don't bring that up at dinner."]},
        ],
    },
    {
        "id": "weekend-plan",
        "title": "跟朋友約週末爬山",
        "level": "A2-B1",
        "scene": "禮拜三在 LINE 上敲朋友週末有沒有空",
        "lines": [
            {"speaker": "你", "en": "Hey, are you free this Saturday?",
             "zh": "嘿，這週六有空嗎？"},
            {"speaker": "朋友", "en": "I think so. What's up?",
             "zh": "應該有，怎麼了？"},
            {"speaker": "你", "en": "A few of us are going hiking. Want to come?",
             "zh": "我們幾個要去爬山，你要一起嗎？"},
            {"speaker": "朋友", "en": "That sounds fun! Where are you going?",
             "zh": "聽起來不錯！要去哪？"},
            {"speaker": "你", "en": "Yangmingshan, the easy trail. We'll start around 9.",
             "zh": "陽明山，走簡單的路線。九點左右出發。"},
            {"speaker": "朋友", "en": "Cool. Should I bring anything?",
             "zh": "好。要帶什麼嗎？"},
            {"speaker": "你", "en": "Maybe water and a snack. We're getting lunch after.",
             "zh": "水跟點心吧，午餐回來再吃。"},
            {"speaker": "朋友", "en": "Got it. Let's meet at the MRT station?",
             "zh": "了解。我們在捷運站碰面？"},
            {"speaker": "你", "en": "Sure, see you at 8:45 then.",
             "zh": "好，那 8:45 見。"},
        ],
        "grammar": [
            {"point": "Are you free + 時間?",
             "explain": "問對方有無空檔的標準說法。比 'Do you have time?' 自然。",
             "examples": ["Are you free this Saturday?",
                          "Are you free tonight?",
                          "Are you free for lunch tomorrow?"]},
            {"point": "Want to + V? / Wanna ...?",
             "explain": "非正式邀請,省略 Do you。Want to 在口語常縮成 wanna。",
             "examples": ["Want to come?", "Wanna grab dinner?",
                          "Wanna come over for a movie?"]},
            {"point": "Should I bring anything?",
             "explain": "去別人家／聚會時的禮貌問句。回答常是 'Just yourself' 或具體物品。",
             "examples": ["Should I bring anything?",
                          "What should I wear?",
                          "Should I bring my laptop?"]},
            {"point": "現在進行式表未來",
             "explain": "be + Ving 也能表「已定好的未來計畫」,語感比 will 更確定。",
             "examples": ["A few of us are going hiking.",
                          "I'm meeting Sara at 7.",
                          "We're flying to Japan next month."]},
        ],
    },
]


STORIES = [
    {
        "id": "morning-routine",
        "title": "My Morning Routine",
        "level": "A2",
        "scene": "用現在式練習描述每天的習慣",
        "paragraphs": [
            {"en": "I usually wake up at 7 AM. As soon as my alarm rings, I drink a big glass of water. Then I go to the bathroom and brush my teeth.",
             "zh": "我通常早上 7 點起床。鬧鐘一響我就喝一大杯水，然後去浴室刷牙。"},
            {"en": "I prefer cold showers because they wake me up fast. Around 7:30, I make a quick breakfast — usually toast and eggs.",
             "zh": "我喜歡洗冷水澡，因為能很快醒過來。7:30 左右我做個簡單的早餐，通常是吐司加蛋。"},
            {"en": "While I eat, I check my phone for messages. After breakfast, I get dressed and pack my bag for work.",
             "zh": "邊吃邊看手機訊息。吃完早餐後，我換衣服、準備上班用的包包。"},
            {"en": "I leave the house at 8:15 to catch the bus. The ride takes about 30 minutes, so I usually listen to a podcast or read a book.",
             "zh": "8:15 出門去搭公車。車程大約 30 分鐘，我通常聽 podcast 或看書。"},
            {"en": "By 9 AM, I'm at my desk and ready to start the day. It's a simple routine, but it keeps me organized.",
             "zh": "九點前我就坐到位子上，準備好開始工作。這個習慣很簡單，但讓我生活很有條理。"},
        ],
        "grammar": [
            {"point": "Simple Present 現在式 — 描述習慣／日常",
             "explain": "重複發生的事用現在式,動詞用原形（第三人稱單數加 s/es）。"
                        "搭配 usually / always / often / every day。",
             "examples": ["I usually wake up at 7 AM.",
                          "She drinks coffee every morning.",
                          "We go to the gym on weekends."]},
            {"point": "as soon as ... — 「一…就…」",
             "explain": "時間連接詞,兩個動作緊接著發生。子句用現在式（即使指未來）。",
             "examples": ["As soon as my alarm rings, I drink water.",
                          "Call me as soon as you arrive.",
                          "She left as soon as it started raining."]},
            {"point": "時間介系詞 at / around / by",
             "explain": "at 用於精確時間（at 7 AM）；around 用於大約（around 7:30）；"
                        "by 用於「在…之前／到…為止」(by 9 AM = 不晚於 9 點)。",
             "examples": ["I wake up at 7 AM.",
                          "Around 7:30, I make breakfast.",
                          "By 9 AM, I'm at my desk."]},
            {"point": "While + 子句 / After + 名詞",
             "explain": "while 表「在…同時」(後接子句);after 後可接名詞或子句。",
             "examples": ["While I eat, I check my phone.",
                          "After breakfast, I get dressed.",
                          "After I finished work, I went home."]},
        ],
    },
    {
        "id": "best-trip",
        "title": "The Best Trip I Ever Took",
        "level": "B1",
        "scene": "用過去式與完成式講一段回憶",
        "paragraphs": [
            {"en": "Two summers ago, I went to Kyoto with my best friend. It was my first time visiting Japan, and I had been dreaming about it for years.",
             "zh": "兩年前的夏天，我跟最好的朋友去京都。那是我第一次去日本，我已經夢想了好多年。"},
            {"en": "We stayed in a small ryokan in Gion. The host welcomed us with green tea and rice crackers. That evening, we walked through the old streets, and I felt like I had stepped into a movie.",
             "zh": "我們住在祇園的一家小旅館。老闆娘用抹茶跟米菓招待我們。那天傍晚我們走過古老的街道，我覺得自己彷彿走進了一部電影。"},
            {"en": "The next day, we visited Fushimi Inari Shrine. Climbing all those red gates took almost three hours, but the view from the top was worth every step. I had never seen anything so beautiful.",
             "zh": "隔天我們去了伏見稻荷大社。爬完那些紅色鳥居花了快三小時，但山頂的景色每一步都值得。我從沒見過這麼美的景色。"},
            {"en": "By the end of the trip, I'd taken over 500 photos. We promised each other we'd go back someday. I haven't made it yet, but I will.",
             "zh": "旅程結束時，我已經拍了 500 多張照片。我們約定有一天要再回去。雖然到現在還沒實現，但我一定會的。"},
        ],
        "grammar": [
            {"point": "Past Simple 過去簡單式 — 已完成的單一事件",
             "explain": "動詞變過去式 (went / stayed / visited / took)。"
                        "敘述故事的主幹時態,通常搭配明確時間（two summers ago, that evening）。",
             "examples": ["I went to Kyoto.",
                          "We stayed in a ryokan.",
                          "We visited the shrine."]},
            {"point": "Past Perfect 過去完成式 — 「過去的過去」",
             "explain": "had + 過去分詞。表示某動作在「另一個過去事件」之前就完成了。"
                        "常與 had been ... for years（已經…好幾年了）一起用。",
             "examples": ["I had been dreaming about it for years.",
                          "I felt like I had stepped into a movie.",
                          "I had never seen anything so beautiful."]},
            {"point": "Present Perfect 現在完成式 — 從過去持續到現在",
             "explain": "have/has + 過去分詞。表示「到現在為止」的狀態或未完成的事。"
                        "haven't ... yet 是「還沒…」的固定組合。",
             "examples": ["I haven't made it back yet.",
                          "I've been to Japan twice.",
                          "She has never tried sushi."]},
            {"point": "would 表「過去的未來」",
             "explain": "在過去視角下講「會做的事」,常用於間接引述。"
                        "We promised we'd go back = We promised we would go back。",
             "examples": ["We promised we'd go back.",
                          "He said he would call.",
                          "I knew it would be hard."]},
        ],
    },
]
