"""閱讀本資料(離線、不需 API)。
每篇有 sentences[],每句含 en / zh / vocab(逐字翻譯) / phrases(多字片語)。
view_reading 渲染成可點字看翻譯、可點句子看整句翻譯的互動 HTML。
"""

READINGS = [
    {
        "id": "morning-cafe",
        "title": "A Quiet Morning Cafe",
        "title_zh": "靜謐的晨間咖啡廳",
        "level": "A2",
        "summary": "用簡單現在式描述一家小咖啡廳的早晨——適合練「日常觀察」短文",
        "sentences": [
            {
                "en": "Every morning, I walk past a small cafe on my way to work.",
                "zh": "每天早上，我走路上班的時候會經過一間小咖啡廳。",
                "vocab": {
                    "every": "每個",
                    "morning": "早上",
                    "walk": "走（動詞）",
                    "past": "經過、過去",
                    "small": "小的",
                    "cafe": "咖啡廳",
                    "way": "路、方式",
                    "work": "工作、上班",
                },
                "phrases": [
                    {"en": "every morning", "zh": "每天早上"},
                    {"en": "walk past", "zh": "走過、經過（phrasal verb）"},
                    {"en": "on my way to", "zh": "在我去…的路上"},
                ],
            },
            {
                "en": "The smell of fresh coffee always makes me stop for a moment.",
                "zh": "現煮咖啡的香味總是讓我停下腳步一下。",
                "vocab": {
                    "smell": "氣味、聞起來",
                    "fresh": "新鮮的、現做的",
                    "coffee": "咖啡",
                    "always": "總是",
                    "makes": "使（make 的單三）",
                    "stop": "停止",
                    "moment": "片刻、瞬間",
                },
                "phrases": [
                    {"en": "the smell of X", "zh": "X 的味道"},
                    {"en": "make sb. do", "zh": "讓某人做某事（使役動詞）"},
                    {"en": "for a moment", "zh": "一下、片刻"},
                ],
            },
            {
                "en": "The owner is a kind old man who waves at me through the window.",
                "zh": "店主是個和藹的老先生，他會隔著窗戶向我揮手。",
                "vocab": {
                    "owner": "店主、擁有者",
                    "kind": "善良的、和藹的",
                    "old": "年長的、老的",
                    "man": "男人",
                    "who": "誰（關係代名詞）",
                    "waves": "揮（手）",
                    "through": "穿過、透過",
                    "window": "窗戶",
                },
                "phrases": [
                    {"en": "wave at sb.", "zh": "向某人揮手"},
                    {"en": "through the window", "zh": "透過窗戶"},
                ],
            },
            {
                "en": "Sometimes I go inside and order a black coffee.",
                "zh": "有時候我會進去點一杯黑咖啡。",
                "vocab": {
                    "sometimes": "有時候",
                    "go": "去",
                    "inside": "在裡面",
                    "order": "點餐、訂購",
                    "black": "黑的",
                    "coffee": "咖啡",
                },
                "phrases": [
                    {"en": "go inside", "zh": "進去（裡面）"},
                    {"en": "black coffee", "zh": "黑咖啡（不加奶不加糖）"},
                ],
            },
            {
                "en": "He never charges me for the second cup.",
                "zh": "他從不收我第二杯的錢。",
                "vocab": {
                    "never": "從不",
                    "charges": "收費（charge 單三）",
                    "second": "第二的",
                    "cup": "杯",
                },
                "phrases": [
                    {"en": "charge sb. for X", "zh": "向某人收 X 的錢"},
                    {"en": "the second cup", "zh": "第二杯"},
                ],
            },
            {
                "en": "The cafe is quiet, with only soft jazz playing in the background.",
                "zh": "咖啡廳很安靜，只有輕柔的爵士樂在背景播放。",
                "vocab": {
                    "quiet": "安靜的",
                    "only": "只有",
                    "soft": "柔和的、輕的",
                    "jazz": "爵士樂",
                    "playing": "播放（現在分詞）",
                    "background": "背景",
                },
                "phrases": [
                    {"en": "with X playing", "zh": "伴隨 X 播放（with + 名詞 + 分詞）"},
                    {"en": "in the background", "zh": "在背景"},
                ],
            },
            {
                "en": "It feels like a small escape from the busy city.",
                "zh": "感覺像是從繁忙城市裡的一個小小逃離。",
                "vocab": {
                    "feels": "感覺（feel 單三）",
                    "like": "像（介系詞）",
                    "small": "小的",
                    "escape": "逃離、解脫",
                    "busy": "繁忙的",
                    "city": "城市",
                },
                "phrases": [
                    {"en": "feel like X", "zh": "感覺像是 X / 想要 X"},
                    {"en": "escape from X", "zh": "從 X 逃離、解脫"},
                ],
            },
            {
                "en": "I think small moments like these are what make life nice.",
                "zh": "我覺得像這樣的小片刻，正是讓生活美好的事。",
                "vocab": {
                    "think": "認為、覺得",
                    "small": "小的",
                    "moments": "時刻（複數）",
                    "like": "像",
                    "these": "這些",
                    "make": "使、讓",
                    "life": "生活、人生",
                    "nice": "美好的、不錯的",
                },
                "phrases": [
                    {"en": "X is what make(s) Y Z", "zh": "X 正是讓 Y 變成 Z 的東西（強調句型）"},
                    {"en": "moments like these", "zh": "像這樣的時刻"},
                ],
            },
        ],
        "grammar": [
            {"point": "Simple Present 現在式 — 描述慣常/事實",
             "explain": "敘述每天重複的習慣或客觀事實時用現在式。第三人稱單數加 s/es。",
             "examples": ["I walk past a cafe every morning.",
                          "The owner waves at me.",
                          "He never charges me."]},
            {"point": "with + 名詞 + 現在分詞（伴隨狀態）",
             "explain": "「with X playing」描述背景同時發生的動作，比兩個獨立句子更精簡。",
             "examples": ["The cafe is quiet, with only soft jazz playing.",
                          "She walked away, with tears running down her face.",
                          "He spoke softly, with his eyes closed."]},
            {"point": "make + sb./sth. + 原形動詞（使役動詞）",
             "explain": "「使...做某事」。make 後接受詞 + 原形動詞，不加 to。",
             "examples": ["The smell makes me stop.",
                          "Music makes her happy.",
                          "Don't make me wait."]},
            {"point": "強調句型：X is what make(s) Y Z",
             "explain": "把焦點放在「正是 X 讓 Y 變成 Z」。用 what 引導關係子句強調原因。",
             "examples": ["Small moments are what make life nice.",
                          "Hard work is what makes him successful.",
                          "Your kindness is what made my day."]},
        ],
    },
    {
        "id": "trip-kyoto",
        "title": "The Trip That Changed My Mind",
        "title_zh": "改變我心意的那次旅行",
        "level": "B1",
        "summary": "個人成長敘事，過去式 + 過去完成式 + 現在完成式混用",
        "sentences": [
            {
                "en": "Two years ago, I traveled alone to Kyoto for the first time.",
                "zh": "兩年前，我第一次獨自前往京都。",
                "vocab": {
                    "two": "兩",
                    "years": "年（複數）",
                    "ago": "以前",
                    "traveled": "旅行（travel 過去式）",
                    "alone": "獨自地",
                    "Kyoto": "京都",
                    "first": "第一",
                    "time": "次、時間",
                },
                "phrases": [
                    {"en": "two years ago", "zh": "兩年前（時間 + ago）"},
                    {"en": "travel alone", "zh": "獨自旅行"},
                    {"en": "for the first time", "zh": "第一次"},
                ],
            },
            {
                "en": "I had always been afraid of going to a new country by myself.",
                "zh": "我一直都很害怕一個人去新的國家。",
                "vocab": {
                    "had": "had + 過去分詞 = 過去完成式",
                    "always": "總是、一直",
                    "been": "be 的過去分詞",
                    "afraid": "害怕的",
                    "going": "去（動名詞）",
                    "new": "新的",
                    "country": "國家",
                    "myself": "我自己（反身代名詞）",
                },
                "phrases": [
                    {"en": "had been afraid of Ving", "zh": "（以前一直）害怕做某事（過去完成式）"},
                    {"en": "by myself", "zh": "獨自、靠自己"},
                ],
            },
            {
                "en": "But after my friends canceled at the last minute, I decided to go anyway.",
                "zh": "但朋友們最後一刻取消了，我還是決定自己去。",
                "vocab": {
                    "but": "但是",
                    "after": "在…之後",
                    "friends": "朋友（複數）",
                    "canceled": "取消（過去式）",
                    "last": "最後的",
                    "minute": "分鐘",
                    "decided": "決定（過去式）",
                    "go": "去",
                    "anyway": "無論如何、還是",
                },
                "phrases": [
                    {"en": "at the last minute", "zh": "在最後一刻（臨時改變）"},
                    {"en": "decide to V", "zh": "決定做某事"},
                    {"en": "go anyway", "zh": "還是去（強調不放棄）"},
                ],
            },
            {
                "en": "The first day was hard — I got lost and missed my train.",
                "zh": "第一天很難——我迷路了還錯過了火車。",
                "vocab": {
                    "first": "第一",
                    "day": "天",
                    "hard": "困難的",
                    "got": "變得（get 過去式）",
                    "lost": "迷路的、迷失的",
                    "missed": "錯過（過去式）",
                    "train": "火車",
                },
                "phrases": [
                    {"en": "get lost", "zh": "迷路"},
                    {"en": "miss a train", "zh": "錯過火車"},
                ],
            },
            {
                "en": "By the third day, however, I had learned to enjoy the silence.",
                "zh": "但是到了第三天，我已經學會享受寧靜。",
                "vocab": {
                    "by": "到…為止",
                    "third": "第三的",
                    "day": "天",
                    "however": "然而（連接副詞）",
                    "had": "had + p.p. 過去完成式",
                    "learned": "學會（learn 過去分詞）",
                    "enjoy": "享受",
                    "silence": "寧靜、沉默",
                },
                "phrases": [
                    {"en": "by the third day", "zh": "到第三天為止"},
                    {"en": "had learned to V", "zh": "（在那之前已經）學會了 V（過去完成式）"},
                    {"en": "enjoy the silence", "zh": "享受寧靜"},
                ],
            },
            {
                "en": "I realized that being alone is not the same as being lonely.",
                "zh": "我發現獨處跟孤單不是同一回事。",
                "vocab": {
                    "realized": "意識到、發現（過去式）",
                    "that": "that 引導名詞子句",
                    "being": "成為、處於（動名詞）",
                    "alone": "獨自的",
                    "same": "相同的",
                    "lonely": "寂寞的、孤單的",
                },
                "phrases": [
                    {"en": "realize that + 子句", "zh": "意識到…"},
                    {"en": "being alone", "zh": "獨處（動名詞作主詞）"},
                    {"en": "the same as X", "zh": "與 X 相同"},
                    {"en": "alone vs lonely", "zh": "alone = 物理上獨自；lonely = 情感上孤單"},
                ],
            },
            {
                "en": "That trip taught me to trust myself, and I've traveled solo ever since.",
                "zh": "那趟旅行教會我相信自己，從那之後我都獨自旅行。",
                "vocab": {
                    "trip": "旅行",
                    "taught": "教（teach 過去式）",
                    "trust": "信任",
                    "myself": "我自己",
                    "traveled": "旅行（過去分詞）",
                    "solo": "獨自地",
                    "ever": "曾經、向來",
                    "since": "從那時起",
                },
                "phrases": [
                    {"en": "teach sb. to V", "zh": "教某人做某事"},
                    {"en": "trust myself", "zh": "相信自己"},
                    {"en": "I've traveled solo ever since", "zh": "從那之後我都獨自旅行（現在完成式）"},
                    {"en": "ever since", "zh": "從那時起一直"},
                ],
            },
        ],
        "grammar": [
            {"point": "Past Perfect 過去完成式 — 「過去的過去」",
             "explain": "had + 過去分詞。表示某動作在「另一個過去事件」之前就已經完成或持續。",
             "examples": ["I had always been afraid of going alone.",
                          "By the third day, I had learned to enjoy the silence.",
                          "She had finished her homework before dinner."]},
            {"point": "Present Perfect 現在完成式 — 從過去持續到現在",
             "explain": "have/has + 過去分詞，搭配 ever since / for years / so far 等強調「到現在」。",
             "examples": ["I've traveled solo ever since.",
                          "I've lived here for ten years.",
                          "She has worked there since 2020."]},
            {"point": "動名詞當主詞 / 受詞 — Being alone is...",
             "explain": "V-ing 形式可作主詞或受詞，視為單數。「being alone」= 獨處這件事。",
             "examples": ["Being alone is not the same as being lonely.",
                          "Learning English takes time.",
                          "She enjoys reading at night."]},
            {"point": "alone vs lonely — 易混淆對比",
             "explain": "alone 偏物理狀態（一個人、無人陪），lonely 偏情緒（寂寞）。"
                        "可以 be alone but not lonely(獨處不寂寞)。",
             "examples": ["I live alone, but I'm not lonely.",
                          "She felt lonely even at the party.",
                          "Sometimes being alone is a gift."]},
            {"point": "Teach sb. to V — 使役/教導句型",
             "explain": "teach 後接「人 + to + 原形動詞」表示「教某人做某事」。"
                        "類似的有 tell / ask / want / help。",
             "examples": ["That trip taught me to trust myself.",
                          "She taught me to swim.",
                          "I'd love to teach you to cook."]},
        ],
    },
]
