"""閱讀本資料(離線、不需 API)。
每篇有 sentences[],每句含 en / zh / vocab(逐字翻譯) / phrases(多字片語)。
view_reading 渲染成可點字看翻譯、可點句子看整句翻譯的互動 HTML。
"""

READINGS = [
    {
        "id": "morning-cafe",
        "title": "A Quiet Morning Cafe",
        "title_zh": "靜謐的晨間咖啡廳",
        "level": "A2",
        "summary": "用簡單現在式描述一家小咖啡廳的早晨——適合練「日常觀察」短文",
        "sentences": [
            {
                "en": "Every morning, I walk past a small cafe on my way to work.",
                "zh": "每天早上，我走路上班的時候會經過一間小咖啡廳。",
                "vocab": {
                    "every": "每個",
                    "morning": "早上",
                    "walk": "走（動詞）",
                    "past": "經過、過去",
                    "small": "小的",
                    "cafe": "咖啡廳",
                    "way": "路、方式",
                    "work": "工作、上班",
                },
                "phrases": [
                    {"en": "every morning", "zh": "每天早上"},
                    {"en": "walk past", "zh": "走過、經過（phrasal verb）"},
                    {"en": "on my way to", "zh": "在我去…的路上"},
                ],
            },
            {
                "en": "The smell of fresh coffee always makes me stop for a moment.",
                "zh": "現煮咖啡的香味總是讓我停下腳步一下。",
                "vocab": {
                    "smell": "氣味、聞起來",
                    "fresh": "新鮮的、現做的",
                    "coffee": "咖啡",
                    "always": "總是",
                    "makes": "使（make 的單三）",
                    "stop": "停止",
                    "moment": "片刻、瞬間",
                },
                "phrases": [
                    {"en": "the smell of X", "zh": "X 的味道"},
                    {"en": "make sb. do", "zh": "讓某人做某事（使役動詞）"},
                    {"en": "for a moment", "zh": "一下、片刻"},
                ],
            },
            {
                "en": "The owner is a kind old man who waves at me through the window.",
                "zh": "店主是個和藹的老先生，他會隔著窗戶向我揮手。",
                "vocab": {
                    "owner": "店主、擁有者",
                    "kind": "善良的、和藹的",
                    "old": "年長的、老的",
                    "man": "男人",
                    "who": "誰（關係代名詞）",
                    "waves": "揮（手）",
                    "through": "穿過、透過",
                    "window": "窗戶",
                },
                "phrases": [
                    {"en": "wave at sb.", "zh": "向某人揮手"},
                    {"en": "through the window", "zh": "透過窗戶"},
                ],
            },
            {
                "en": "Sometimes I go inside and order a black coffee.",
                "zh": "有時候我會進去點一杯黑咖啡。",
                "vocab": {
                    "sometimes": "有時候",
                    "go": "去",
                    "inside": "在裡面",
                    "order": "點餐、訂購",
                    "black": "黑的",
                    "coffee": "咖啡",
                },
                "phrases": [
                    {"en": "go inside", "zh": "進去（裡面）"},
                    {"en": "black coffee", "zh": "黑咖啡（不加奶不加糖）"},
                ],
            },
            {
                "en": "He never charges me for the second cup.",
                "zh": "他從不收我第二杯的錢。",
                "vocab": {
                    "never": "從不",
                    "charges": "收費（charge 單三）",
                    "second": "第二的",
                    "cup": "杯",
                },
                "phrases": [
                    {"en": "charge sb. for X", "zh": "向某人收 X 的錢"},
                    {"en": "the second cup", "zh": "第二杯"},
                ],
            },
            {
                "en": "The cafe is quiet, with only soft jazz playing in the background.",
                "zh": "咖啡廳很安靜，只有輕柔的爵士樂在背景播放。",
                "vocab": {
                    "quiet": "安靜的",
                    "only": "只有",
                    "soft": "柔和的、輕的",
                    "jazz": "爵士樂",
                    "playing": "播放（現在分詞）",
                    "background": "背景",
                },
                "phrases": [
                    {"en": "with X playing", "zh": "伴隨 X 播放（with + 名詞 + 分詞）"},
                    {"en": "in the background", "zh": "在背景"},
                ],
            },
            {
                "en": "It feels like a small escape from the busy city.",
                "zh": "感覺像是從繁忙城市裡的一個小小逃離。",
                "vocab": {
                    "feels": "感覺（feel 單三）",
                    "like": "像（介系詞）",
                    "small": "小的",
                    "escape": "逃離、解脫",
                    "busy": "繁忙的",
                    "city": "城市",
                },
                "phrases": [
                    {"en": "feel like X", "zh": "感覺像是 X / 想要 X"},
                    {"en": "escape from X", "zh": "從 X 逃離、解脫"},
                ],
            },
            {
                "en": "I think small moments like these are what make life nice.",
                "zh": "我覺得像這樣的小片刻，正是讓生活美好的事。",
                "vocab": {
                    "think": "認為、覺得",
                    "small": "小的",
                    "moments": "時刻（複數）",
                    "like": "像",
                    "these": "這些",
                    "make": "使、讓",
                    "life": "生活、人生",
                    "nice": "美好的、不錯的",
                },
                "phrases": [
                    {"en": "X is what make(s) Y Z", "zh": "X 正是讓 Y 變成 Z 的東西（強調句型）"},
                    {"en": "moments like these", "zh": "像這樣的時刻"},
                ],
            },
        ],
        "grammar": [
            {"point": "Simple Present 現在式 — 描述慣常/事實",
             "explain": "敘述每天重複的習慣或客觀事實時用現在式。第三人稱單數加 s/es。",
             "examples": ["I walk past a cafe every morning.",
                          "The owner waves at me.",
                          "He never charges me."]},
            {"point": "with + 名詞 + 現在分詞（伴隨狀態）",
             "explain": "「with X playing」描述背景同時發生的動作，比兩個獨立句子更精簡。",
             "examples": ["The cafe is quiet, with only soft jazz playing.",
                          "She walked away, with tears running down her face.",
                          "He spoke softly, with his eyes closed."]},
            {"point": "make + sb./sth. + 原形動詞（使役動詞）",
             "explain": "「使...做某事」。make 後接受詞 + 原形動詞，不加 to。",
             "examples": ["The smell makes me stop.",
                          "Music makes her happy.",
                          "Don't make me wait."]},
            {"point": "強調句型：X is what make(s) Y Z",
             "explain": "把焦點放在「正是 X 讓 Y 變成 Z」。用 what 引導關係子句強調原因。",
             "examples": ["Small moments are what make life nice.",
                          "Hard work is what makes him successful.",
                          "Your kindness is what made my day."]},
        ],
    },
    {
        "id": "trip-kyoto",
        "title": "The Trip That Changed My Mind",
        "title_zh": "改變我心意的那次旅行",
        "level": "B1",
        "summary": "個人成長敘事，過去式 + 過去完成式 + 現在完成式混用",
        "sentences": [
            {
                "en": "Two years ago, I traveled alone to Kyoto for the first time.",
                "zh": "兩年前，我第一次獨自前往京都。",
                "vocab": {
                    "two": "兩",
                    "years": "年（複數）",
                    "ago": "以前",
                    "traveled": "旅行（travel 過去式）",
                    "alone": "獨自地",
                    "Kyoto": "京都",
                    "first": "第一",
                    "time": "次、時間",
                },
                "phrases": [
                    {"en": "two years ago", "zh": "兩年前（時間 + ago）"},
                    {"en": "travel alone", "zh": "獨自旅行"},
                    {"en": "for the first time", "zh": "第一次"},
                ],
            },
            {
                "en": "I had always been afraid of going to a new country by myself.",
                "zh": "我一直都很害怕一個人去新的國家。",
                "vocab": {
                    "had": "had + 過去分詞 = 過去完成式",
                    "always": "總是、一直",
                    "been": "be 的過去分詞",
                    "afraid": "害怕的",
                    "going": "去（動名詞）",
                    "new": "新的",
                    "country": "國家",
                    "myself": "我自己（反身代名詞）",
                },
                "phrases": [
                    {"en": "had been afraid of Ving", "zh": "（以前一直）害怕做某事（過去完成式）"},
                    {"en": "by myself", "zh": "獨自、靠自己"},
                ],
            },
            {
                "en": "But after my friends canceled at the last minute, I decided to go anyway.",
                "zh": "但朋友們最後一刻取消了，我還是決定自己去。",
                "vocab": {
                    "but": "但是",
                    "after": "在…之後",
                    "friends": "朋友（複數）",
                    "canceled": "取消（過去式）",
                    "last": "最後的",
                    "minute": "分鐘",
                    "decided": "決定（過去式）",
                    "go": "去",
                    "anyway": "無論如何、還是",
                },
                "phrases": [
                    {"en": "at the last minute", "zh": "在最後一刻（臨時改變）"},
                    {"en": "decide to V", "zh": "決定做某事"},
                    {"en": "go anyway", "zh": "還是去（強調不放棄）"},
                ],
            },
            {
                "en": "The first day was hard — I got lost and missed my train.",
                "zh": "第一天很難——我迷路了還錯過了火車。",
                "vocab": {
                    "first": "第一",
                    "day": "天",
                    "hard": "困難的",
                    "got": "變得（get 過去式）",
                    "lost": "迷路的、迷失的",
                    "missed": "錯過（過去式）",
                    "train": "火車",
                },
                "phrases": [
                    {"en": "get lost", "zh": "迷路"},
                    {"en": "miss a train", "zh": "錯過火車"},
                ],
            },
            {
                "en": "By the third day, however, I had learned to enjoy the silence.",
                "zh": "但是到了第三天，我已經學會享受寧靜。",
                "vocab": {
                    "by": "到…為止",
                    "third": "第三的",
                    "day": "天",
                    "however": "然而（連接副詞）",
                    "had": "had + p.p. 過去完成式",
                    "learned": "學會（learn 過去分詞）",
                    "enjoy": "享受",
                    "silence": "寧靜、沉默",
                },
                "phrases": [
                    {"en": "by the third day", "zh": "到第三天為止"},
                    {"en": "had learned to V", "zh": "（在那之前已經）學會了 V（過去完成式）"},
                    {"en": "enjoy the silence", "zh": "享受寧靜"},
                ],
            },
            {
                "en": "I realized that being alone is not the same as being lonely.",
                "zh": "我發現獨處跟孤單不是同一回事。",
                "vocab": {
                    "realized": "意識到、發現（過去式）",
                    "that": "that 引導名詞子句",
                    "being": "成為、處於（動名詞）",
                    "alone": "獨自的",
                    "same": "相同的",
                    "lonely": "寂寞的、孤單的",
                },
                "phrases": [
                    {"en": "realize that + 子句", "zh": "意識到…"},
                    {"en": "being alone", "zh": "獨處（動名詞作主詞）"},
                    {"en": "the same as X", "zh": "與 X 相同"},
                    {"en": "alone vs lonely", "zh": "alone = 物理上獨自；lonely = 情感上孤單"},
                ],
            },
            {
                "en": "That trip taught me to trust myself, and I've traveled solo ever since.",
                "zh": "那趟旅行教會我相信自己，從那之後我都獨自旅行。",
                "vocab": {
                    "trip": "旅行",
                    "taught": "教（teach 過去式）",
                    "trust": "信任",
                    "myself": "我自己",
                    "traveled": "旅行（過去分詞）",
                    "solo": "獨自地",
                    "ever": "曾經、向來",
                    "since": "從那時起",
                },
                "phrases": [
                    {"en": "teach sb. to V", "zh": "教某人做某事"},
                    {"en": "trust myself", "zh": "相信自己"},
                    {"en": "I've traveled solo ever since", "zh": "從那之後我都獨自旅行（現在完成式）"},
                    {"en": "ever since", "zh": "從那時起一直"},
                ],
            },
        ],
        "grammar": [
            {"point": "Past Perfect 過去完成式 — 「過去的過去」",
             "explain": "had + 過去分詞。表示某動作在「另一個過去事件」之前就已經完成或持續。",
             "examples": ["I had always been afraid of going alone.",
                          "By the third day, I had learned to enjoy the silence.",
                          "She had finished her homework before dinner."]},
            {"point": "Present Perfect 現在完成式 — 從過去持續到現在",
             "explain": "have/has + 過去分詞，搭配 ever since / for years / so far 等強調「到現在」。",
             "examples": ["I've traveled solo ever since.",
                          "I've lived here for ten years.",
                          "She has worked there since 2020."]},
            {"point": "動名詞當主詞 / 受詞 — Being alone is...",
             "explain": "V-ing 形式可作主詞或受詞，視為單數。「being alone」= 獨處這件事。",
             "examples": ["Being alone is not the same as being lonely.",
                          "Learning English takes time.",
                          "She enjoys reading at night."]},
            {"point": "alone vs lonely — 易混淆對比",
             "explain": "alone 偏物理狀態（一個人、無人陪），lonely 偏情緒（寂寞）。"
                        "可以 be alone but not lonely(獨處不寂寞)。",
             "examples": ["I live alone, but I'm not lonely.",
                          "She felt lonely even at the party.",
                          "Sometimes being alone is a gift."]},
            {"point": "Teach sb. to V — 使役/教導句型",
             "explain": "teach 後接「人 + to + 原形動詞」表示「教某人做某事」。"
                        "類似的有 tell / ask / want / help。",
             "examples": ["That trip taught me to trust myself.",
                          "She taught me to swim.",
                          "I'd love to teach you to cook."]},
        ],
    },
    {
        "id": "rainy-saturday",
        "title": "A Rainy Saturday at Home",
        "title_zh": "一個下雨的週六",
        "level": "A2",
        "summary": "現在式 + 天氣表達 + 日常活動描述",
        "sentences": [
            {
                "en": "It is raining outside, so I am staying home today.",
                "zh": "外面在下雨，所以我今天待在家。",
                "vocab": {"raining": "下雨（動詞 ing 形）", "outside": "外面",
                          "staying": "待在（動詞 ing 形）", "home": "家", "today": "今天"},
                "phrases": [{"en": "stay home", "zh": "待在家"},
                            {"en": "it is raining", "zh": "正在下雨（現在進行式描述天氣）"}],
            },
            {
                "en": "I make a hot cup of tea and sit by the window.",
                "zh": "我泡一杯熱茶，坐在窗邊。",
                "vocab": {"make": "做、泡", "hot": "熱的", "cup": "杯",
                          "tea": "茶", "sit": "坐", "window": "窗戶"},
                "phrases": [{"en": "a hot cup of tea", "zh": "一杯熱茶"},
                            {"en": "sit by the window", "zh": "坐在窗邊"}],
            },
            {
                "en": "The sound of rain makes me feel calm.",
                "zh": "雨聲讓我感到很平靜。",
                "vocab": {"sound": "聲音", "rain": "雨", "makes": "使（單三）",
                          "feel": "感覺", "calm": "平靜的"},
                "phrases": [{"en": "the sound of rain", "zh": "雨的聲音"},
                            {"en": "feel calm", "zh": "感到平靜"}],
            },
            {
                "en": "I open a book I have been meaning to read for weeks.",
                "zh": "我打開一本我想看好幾個禮拜的書。",
                "vocab": {"open": "打開", "book": "書", "meaning": "打算（mean 的進行式）",
                          "read": "閱讀", "weeks": "週（複數）"},
                "phrases": [{"en": "have been meaning to V", "zh": "一直想做某事卻沒做（現在完成進行式）"},
                            {"en": "for weeks", "zh": "好幾個禮拜"}],
            },
            {
                "en": "Sometimes a quiet day is exactly what you need.",
                "zh": "有時候安靜的一天正是你需要的。",
                "vocab": {"sometimes": "有時候", "quiet": "安靜的", "day": "一天",
                          "exactly": "正好", "need": "需要"},
                "phrases": [{"en": "exactly what you need", "zh": "正是你所需要的（強調句型）"}],
            },
            {
                "en": "I will probably take a nap before dinner.",
                "zh": "晚餐前我可能會小睡一下。",
                "vocab": {"will": "將會（助動詞）", "probably": "可能",
                          "take": "做、進行", "nap": "小睡", "dinner": "晚餐"},
                "phrases": [{"en": "take a nap", "zh": "小睡片刻"},
                            {"en": "before dinner", "zh": "晚餐前"}],
            },
        ],
        "grammar": [
            {"point": "Present Continuous 現在進行式 — 描述當下正在發生的事",
             "explain": "be 動詞 (am/is/are) + V-ing。常用於天氣、當下動作。",
             "examples": ["It is raining outside.", "I am staying home today.",
                          "She is reading a book."]},
            {"point": "Make + sb. + 形容詞 — 使某人感覺…",
             "explain": "「使役動詞 make」後接受詞 + 形容詞,表示「讓某人感到…」。",
             "examples": ["The rain makes me feel calm.",
                          "His words made me happy.",
                          "Loud music makes her tired."]},
            {"point": "have been meaning to V — 「一直想做卻還沒做」",
             "explain": "現在完成進行式表達「持續的想法」,常用於日常拖延的事。",
             "examples": ["I have been meaning to call you.",
                          "She's been meaning to start exercising.",
                          "We've been meaning to visit them for months."]},
        ],
    },
    {
        "id": "supermarket",
        "title": "At the Supermarket",
        "title_zh": "在超市購物",
        "level": "A2",
        "summary": "購物情境用語 + 量詞 + 詢問價格",
        "sentences": [
            {
                "en": "I go to the supermarket every Sunday morning.",
                "zh": "我每個星期天早上都去超市。",
                "vocab": {"go": "去", "supermarket": "超市", "every": "每個",
                          "Sunday": "星期天", "morning": "早上"},
                "phrases": [{"en": "every Sunday morning", "zh": "每個星期天早上"}],
            },
            {
                "en": "First, I grab a shopping cart at the entrance.",
                "zh": "首先,我在入口處拿一台購物推車。",
                "vocab": {"first": "首先", "grab": "抓、拿", "shopping": "購物",
                          "cart": "推車", "entrance": "入口"},
                "phrases": [{"en": "shopping cart", "zh": "購物推車"},
                            {"en": "at the entrance", "zh": "在入口處"}],
            },
            {
                "en": "I usually need eggs, milk, bread, and some fresh vegetables.",
                "zh": "我通常需要雞蛋、牛奶、麵包,還有一些新鮮蔬菜。",
                "vocab": {"usually": "通常", "need": "需要", "eggs": "雞蛋",
                          "milk": "牛奶", "bread": "麵包", "fresh": "新鮮的",
                          "vegetables": "蔬菜"},
                "phrases": [{"en": "fresh vegetables", "zh": "新鮮蔬菜"}],
            },
            {
                "en": "Excuse me, how much is this bottle of olive oil?",
                "zh": "不好意思,這瓶橄欖油多少錢?",
                "vocab": {"excuse": "原諒", "much": "多少", "bottle": "瓶",
                          "olive": "橄欖", "oil": "油"},
                "phrases": [{"en": "excuse me", "zh": "不好意思（搭話開頭）"},
                            {"en": "how much is X", "zh": "X 多少錢"},
                            {"en": "a bottle of X", "zh": "一瓶 X（量詞）"}],
            },
            {
                "en": "It's on sale today — buy one, get one free.",
                "zh": "今天特價——買一送一。",
                "vocab": {"sale": "特價", "today": "今天", "buy": "買",
                          "get": "得到", "free": "免費的"},
                "phrases": [{"en": "on sale", "zh": "特價中"},
                            {"en": "buy one, get one free", "zh": "買一送一"}],
            },
            {
                "en": "I pay with my credit card and head home.",
                "zh": "我用信用卡付帳,然後回家。",
                "vocab": {"pay": "付款", "credit": "信用", "card": "卡",
                          "head": "前往（動詞）", "home": "家"},
                "phrases": [{"en": "pay with X", "zh": "用 X 付款"},
                            {"en": "credit card", "zh": "信用卡"},
                            {"en": "head home", "zh": "回家（head + 地點）"}],
            },
        ],
        "grammar": [
            {"point": "量詞 a bottle of / a cup of / a piece of",
             "explain": "不可數名詞前用量詞:a bottle of water、a cup of coffee、a piece of bread。",
             "examples": ["a bottle of olive oil",
                          "a cup of coffee",
                          "a piece of advice"]},
            {"point": "How much / How many — 詢問數量",
             "explain": "how much 問不可數（金錢、液體）;how many 問可數（人、物件）。",
             "examples": ["How much is this?", "How much milk do you need?",
                          "How many eggs are in the box?"]},
            {"point": "head + 地點 — 動詞當「前往」用",
             "explain": "口語中 head 可作動詞,表「往某處去」,比 go 更生動。常見 head home / head out / head to work。",
             "examples": ["I head home at 6.",
                          "Let's head out.",
                          "She heads to work by bus."]},
        ],
    },
    {
        "id": "why-quit-social-media",
        "title": "Why I Stopped Using Social Media",
        "title_zh": "為什麼我戒掉社群媒體",
        "level": "B1",
        "summary": "現在完成式 + 因果敘事 + 現代生活反思",
        "sentences": [
            {
                "en": "Six months ago, I deleted all of my social media apps.",
                "zh": "六個月前,我刪掉了所有的社群媒體 app。",
                "vocab": {"months": "月（複數）", "ago": "以前", "deleted": "刪除（過去式）",
                          "social": "社交的", "media": "媒體", "apps": "應用程式"},
                "phrases": [{"en": "social media", "zh": "社群媒體"},
                            {"en": "X months ago", "zh": "X 個月前"}],
            },
            {
                "en": "I had been spending nearly three hours a day scrolling.",
                "zh": "我那時每天花將近三小時在滑手機。",
                "vocab": {"had": "had + been + Ving（過去完成進行式）", "spending": "花費",
                          "nearly": "將近", "hours": "小時", "scrolling": "滑（手機）"},
                "phrases": [{"en": "spend X scrolling", "zh": "花 X 時間滑手機"},
                            {"en": "three hours a day", "zh": "每天三小時"}],
            },
            {
                "en": "At first, I felt anxious and reached for my phone constantly.",
                "zh": "一開始,我覺得焦慮,還會一直想拿手機。",
                "vocab": {"first": "首先", "felt": "感覺（feel 過去式）", "anxious": "焦慮的",
                          "reached": "伸手（過去式）", "phone": "手機", "constantly": "不斷地"},
                "phrases": [{"en": "at first", "zh": "起初、一開始"},
                            {"en": "reach for X", "zh": "伸手去拿 X"}],
            },
            {
                "en": "But after two weeks, I noticed I was sleeping better.",
                "zh": "但過了兩週,我發現自己睡得比較好了。",
                "vocab": {"after": "之後", "weeks": "週（複數）", "noticed": "注意到",
                          "sleeping": "睡覺", "better": "更好"},
                "phrases": [{"en": "I noticed (that)...", "zh": "我注意到…"},
                            {"en": "sleeping better", "zh": "睡得比較好"}],
            },
            {
                "en": "I have read more books this year than in the past five years combined.",
                "zh": "今年我看過的書比過去五年加起來還多。",
                "vocab": {"have": "have + p.p. 現在完成式", "read": "讀（過去分詞）",
                          "books": "書", "year": "年", "past": "過去的",
                          "five": "五", "years": "年（複數）", "combined": "加起來"},
                "phrases": [{"en": "more X than Y", "zh": "比 Y 多的 X"},
                            {"en": "in the past five years combined", "zh": "過去五年加起來"}],
            },
            {
                "en": "The hardest part was missing out, but the best part was getting my mind back.",
                "zh": "最難的部分是擔心錯過,但最棒的部分是找回我的腦袋。",
                "vocab": {"hardest": "最難的", "part": "部分", "missing": "錯過（V-ing）",
                          "best": "最好的", "getting": "拿到（V-ing）", "mind": "心智、腦袋",
                          "back": "回來"},
                "phrases": [{"en": "miss out", "zh": "錯過（特指 FOMO 那種害怕錯過）"},
                            {"en": "get X back", "zh": "找回 X"}],
            },
        ],
        "grammar": [
            {"point": "Past Perfect Continuous 過去完成進行式 — had been + Ving",
             "explain": "強調「過去某時間點之前一直持續到那時的動作」,常用在反思過去習慣。",
             "examples": ["I had been spending three hours a day scrolling.",
                          "She had been working there for ten years.",
                          "We had been waiting for an hour when he arrived."]},
            {"point": "Present Perfect 現在完成式 — 「到目前為止」的成果",
             "explain": "have/has + p.p.。本文用於講述戒社群後的成果（讀更多書）。",
             "examples": ["I have read more books this year.",
                          "She has learned three languages so far.",
                          "We've made a lot of progress."]},
            {"point": "miss out / get X back — 兩個高頻 phrasal verb",
             "explain": "miss out = 錯過機會（FOMO 那種）;get X back = 找回 X。"
                        "都是 B1/B2 必備口語。",
             "examples": ["I'm worried about missing out.",
                          "Don't miss out on this chance.",
                          "I want to get my old life back."]},
            {"point": "The X part is / was Y — 強調某面向",
             "explain": "把焦點放在某個「方面」用 The X part 句型,可雙重對比（hardest / best）。",
             "examples": ["The hardest part was missing out.",
                          "The fun part is meeting new people.",
                          "The best part of the day is morning coffee."]},
        ],
    },
    {
        "id": "daily-routine",
        "title": "My Weekday Routine",
        "title_zh": "我的平日作息",
        "level": "A2",
        "summary": "現在式 + 頻率副詞 + 時間表達,練「描述每天作息」",
        "sentences": [
            {
                "en": "I usually wake up at seven o'clock on weekdays.",
                "zh": "平日我通常七點起床。",
                "vocab": {"usually": "通常", "wake": "醒來", "weekdays": "平日"},
                "phrases": [{"en": "wake up", "zh": "起床、醒來"},
                            {"en": "on weekdays", "zh": "在平日"}],
            },
            {
                "en": "After a quick breakfast, I take the bus to the office.",
                "zh": "快速吃完早餐後,我搭公車去辦公室。",
                "vocab": {"quick": "快速的", "breakfast": "早餐", "office": "辦公室"},
                "phrases": [{"en": "take the bus", "zh": "搭公車"},
                            {"en": "after + N/Ving", "zh": "在…之後"}],
            },
            {
                "en": "I always check my emails before the morning meeting.",
                "zh": "我總是在晨會前查看電子郵件。",
                "vocab": {"always": "總是", "check": "檢查、查看", "meeting": "會議"},
                "phrases": [{"en": "check emails", "zh": "查看郵件"},
                            {"en": "before the meeting", "zh": "會議前"}],
            },
            {
                "en": "At noon, I often have lunch with my coworkers.",
                "zh": "中午我經常和同事一起吃午餐。",
                "vocab": {"noon": "中午", "often": "經常", "coworkers": "同事"},
                "phrases": [{"en": "have lunch", "zh": "吃午餐"},
                            {"en": "at noon", "zh": "在中午"}],
            },
            {
                "en": "I rarely work late because I value my free time.",
                "zh": "我很少加班,因為我重視我的自由時間。",
                "vocab": {"rarely": "很少", "late": "晚的", "value": "重視", "free": "自由的"},
                "phrases": [{"en": "work late", "zh": "加班、工作到很晚"},
                            {"en": "free time", "zh": "空閒時間"}],
            },
            {
                "en": "In the evening, I cook dinner and then relax with a book.",
                "zh": "晚上我做晚餐,然後看書放鬆。",
                "vocab": {"evening": "傍晚、晚上", "cook": "煮", "relax": "放鬆"},
                "phrases": [{"en": "in the evening", "zh": "在晚上"},
                            {"en": "relax with a book", "zh": "看書放鬆"}],
            },
        ],
        "grammar": [
            {"point": "頻率副詞 always / usually / often / rarely",
             "explain": "頻率副詞放在一般動詞前、be 動詞後,表示動作多常發生。"
                        "由高到低:always > usually > often > sometimes > rarely > never。",
             "examples": ["I always check my emails.",
                          "She usually wakes up early.",
                          "We rarely eat out."]},
            {"point": "時間介系詞 at / in / on",
             "explain": "at 用於精確時間點(at noon);in 用於一段時間(in the evening);on 用於日子(on weekdays)。",
             "examples": ["at seven o'clock", "in the morning", "on Monday"]},
        ],
    },
    {
        "id": "learning-to-cook",
        "title": "How I Learned to Cook",
        "title_zh": "我如何學會做菜",
        "level": "B1",
        "summary": "過去式 + 現在完成式 + 表達進步,練「描述學習一項技能」",
        "sentences": [
            {
                "en": "A year ago, I couldn't even boil an egg properly.",
                "zh": "一年前,我連蛋都煮不好。",
                "vocab": {"ago": "以前", "boil": "煮(沸)", "properly": "妥當地"},
                "phrases": [{"en": "couldn't even V", "zh": "連…都不會(強調程度)"},
                            {"en": "a year ago", "zh": "一年前"}],
            },
            {
                "en": "I decided to learn because eating out was getting expensive.",
                "zh": "我決定學做菜,因為外食變得越來越貴。",
                "vocab": {"decided": "決定", "expensive": "昂貴的"},
                "phrases": [{"en": "decide to V", "zh": "決定做某事"},
                            {"en": "eat out", "zh": "外食、上館子"},
                            {"en": "be getting + 形容詞", "zh": "變得越來越…"}],
            },
            {
                "en": "At first, I followed simple recipes from YouTube videos.",
                "zh": "起初,我跟著 YouTube 影片上的簡單食譜做。",
                "vocab": {"first": "首先", "followed": "跟隨", "recipes": "食譜"},
                "phrases": [{"en": "at first", "zh": "起初"},
                            {"en": "follow a recipe", "zh": "照食譜做"}],
            },
            {
                "en": "I burned a few dishes, but I didn't give up.",
                "zh": "我燒焦了幾道菜,但我沒有放棄。",
                "vocab": {"burned": "燒焦", "dishes": "菜餚", "give": "給"},
                "phrases": [{"en": "give up", "zh": "放棄"},
                            {"en": "a few", "zh": "一些(可數)"}],
            },
            {
                "en": "Now I have cooked for my friends several times.",
                "zh": "現在我已經為朋友下廚好幾次了。",
                "vocab": {"now": "現在", "cooked": "煮(過去分詞)", "several": "好幾個"},
                "phrases": [{"en": "have cooked", "zh": "已經煮過(現在完成式)"},
                            {"en": "several times", "zh": "好幾次"}],
            },
            {
                "en": "Cooking has become my favorite way to relax after work.",
                "zh": "做菜已經成為我下班後最愛的放鬆方式。",
                "vocab": {"become": "成為", "favorite": "最愛的", "relax": "放鬆"},
                "phrases": [{"en": "has become", "zh": "已經成為(現在完成式)"},
                            {"en": "a way to V", "zh": "做某事的方法"}],
            },
        ],
        "grammar": [
            {"point": "could / couldn't — 過去的能力",
             "explain": "could 表示過去有能力做某事,couldn't 表示過去做不到。"
                        "couldn't even V 強調「連…都不會」。",
             "examples": ["I couldn't even boil an egg.",
                          "She could read at age four.",
                          "We couldn't find the way."]},
            {"point": "Present Perfect 現在完成式 — 經驗與成果",
             "explain": "have/has + 過去分詞,搭配 several times / now 強調「到目前累積的經驗」。",
             "examples": ["I have cooked for my friends several times.",
                          "Cooking has become my hobby.",
                          "He has visited Japan twice."]},
            {"point": "be getting + 形容詞 — 「越來越…」",
             "explain": "用現在進行式表達逐漸的變化,形容詞可用比較級加強。",
             "examples": ["Eating out was getting expensive.",
                          "It's getting cold.",
                          "My English is getting better."]},
        ],
    },
]
